Changed the input.nml so it does not reference the deprecated IJK business. Moved the sampling error correction section to be first so that if the ensemble size is not supported the script will die before advancing all the instances.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/branches/rma_trunk@10720 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 466781f4edd83c07b8b7f20ce4b69c2080251516

diff --git a/models/ROMS/shell_scripts/cycle.csh.template b/models/ROMS/shell_scripts/cycle.csh.template
--- a/models/ROMS/shell_scripts/cycle.csh.template
+++ b/models/ROMS/shell_scripts/cycle.csh.template
@@ -54,11 +54,44 @@
 #PBS -q dedicated
 #PBS -l nodes=10:ppn=2
 
+cd EXPERIMENT_DIRECTORY
+
 #=========================================================================
-# STEP 1: Advance the ocean ensemble ... one after another.
+# STEP 1: Stage the file for SAMPLING ERROR CORRECTION if needed.
+#
+# The sampling error correction is a lookup table.
+# The tables are in the DART distribution and have been staged to
+# EXPERIMENT_DIRECTORY by stage_experiment.csh
+# Each ensemble size has its own (static) file. It is only needed if
+# input.nml:&assim_tools_nml:sampling_error_correction = .true.,
+#
+# This is easy to check - and since it is a fatal error to have an ensemble
+# size that is not supported, we die before we advance the model.
 #=========================================================================
 
-cd EXPERIMENT_DIRECTORY
+set ensemble_size = `find instance_???? -type d -print | wc -l`
+
+\cp input.nml.template input.nml
+
+set  MYSTRING = `grep 'sampling_error_correction' input.nml`
+set  MYSTRING = `echo $MYSTRING | sed -e "s#[=,'\.]# #g"`
+set  MYSTRING = `echo $MYSTRING | sed -e 's#"# #g'`
+set SECSTRING = `echo $MYSTRING[2] | tr '[:upper:]' '[:lower:]'`
+
+if ( $SECSTRING == true ) then
+   set SAMP_ERR_FILE = final_full.${ensemble_size}
+   if (! -e  ${SAMP_ERR_FILE} ) then
+      echo "ERROR: no sampling error correction file for this ensemble size."
+      echo "ERROR: looking for ${SAMP_ERR_FILE}"
+      exit 2
+   endif
+else
+   echo "Sampling Error Correction not requested for this assimilation."
+endif
+
+#=========================================================================
+# STEP 2: Advance the ocean ensemble ... one after another.
+#=========================================================================
 
 @ instance = 0
 foreach INSTANCE_DIRECTORY ( instance_???? )
@@ -120,39 +153,6 @@ foreach INSTANCE_DIRECTORY ( instance_???? )
 
 end
 
-set ensemble_size = $instance
-
-#=========================================================================
-# STEP 2: Stage the file for SAMPLING ERROR CORRECTION if needed.
-#
-# The sampling error correction is a lookup table.
-# The tables are in the DART distribution and have been staged to
-# EXPERIMENT_DIRECTORY by stage_experiment.csh
-# Each ensemble size has its own (static) file. It is only needed if
-# input.nml:&assim_tools_nml:sampling_error_correction = .true.,
-#=========================================================================
-
-# The input.nml may be modified differently for each assimilation cycle.
-# (for example, inflation files for the first cycle)
-
-\cp input.nml.template input.nml
-
-set  MYSTRING = `grep 'sampling_error_correction' input.nml`
-set  MYSTRING = `echo $MYSTRING | sed -e "s#[=,'\.]# #g"`
-set  MYSTRING = `echo $MYSTRING | sed -e 's#"# #g'`
-set SECSTRING = `echo $MYSTRING[2] | tr '[:upper:]' '[:lower:]'`
-
-if ( $SECSTRING == true ) then
-   set SAMP_ERR_FILE = final_full.${ensemble_size}
-   if (! -e  ${SAMP_ERR_FILE} ) then
-      echo "ERROR: no sampling error correction file for this ensemble size."
-      echo "ERROR: looking for ${SAMP_ERR_FILE}"
-      exit 2
-   endif
-else
-   echo "Sampling Error Correction not requested for this assimilation."
-endif
-
 #=========================================================================
 # STEP 3: prepare for DART INFLATION
 # This stages the files that contain the inflation values.
@@ -192,6 +192,9 @@ endif
 #
 # The strategy is to use the LATEST (last) inflation file.
 #=========================================================================
+
+# The input.nml may be modified differently for each assimilation cycle.
+# (for example, inflation files for the first cycle)
 
 # These are used to determine IF we are doing inflation.
 
