changed types_mod constants to uppercase, improved run-time logging, and added necessary CVS tags to new components
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/trunk@709 dfa8782c-da17-4c45-ba5c-5625b50a00d6

diff --git a/shell_scripts/MakeICs b/shell_scripts/MakeICs
--- a/shell_scripts/MakeICs
+++ b/shell_scripts/MakeICs
@@ -83,9 +83,9 @@ set SAVEME = .NamelistStorage.$$
 if ( ! -d $SAVEME ) then
    mkdir ${SAVEME}
 endif
-foreach FILE ( *.nml *default )
-   mv -f *.nml ${SAVEME}
-end
+mv -f *.nml         ${SAVEME}
+mv -f *.nml_default ${SAVEME}
+
 echo 'Saved all existing *.nml into directory '"$SAVEME"
 echo 'Will restore and remove the directory at the end.'
 
@@ -96,21 +96,25 @@ echo 'Will restore and remove the directory at the end.'
 # script just sets some of them and takes the defaults on the rest.
 #======================================================================
 
-if !( -e create_obs_set_def ) then
-   csh mkmf_create_obs_set_def
-   make || exit 1
-endif
 if !( -e create_obs_sequence ) then
    csh mkmf_create_obs_sequence
    make || exit 1
+   \rm -f input.nml.create_obs_sequence_default
+endif
+if !( -e create_fixed_network_seq ) then
+   csh mkmf_create_fixed_network_seq
+   make || exit 2
+   \rm -f input.nml.create_fixed_network_seq_default
 endif
 if !( -e perfect_model_obs ) then
    csh mkmf_perfect_model_obs
-   make || exit 1
+   make || exit 3
+   \rm -f input.nml.perfect_model_obs_default
 endif
 if !( -e filter ) then
    csh mkmf_filter
-   make || exit 1
+   make || exit 4
+   \rm -f input.nml.filter_default
 endif
 \rm -f *.o *.mod Makefile
 
@@ -120,25 +124,29 @@ endif
 
 set BINARY_RESTART_FILES = .false.
 
-set COSD = create_obs_set_def.in
 set COS = create_obs_sequence.in
+set CFN = create_fixed_network_seq.in
 
 switch ( ${Model} )
 
    case 9var:
 
-      echo "set_def.out"   > $COSD ;# output file name
-      echo "1"            >> $COSD ;# # of unique observation SETS to define
-      echo "1"            >> $COSD ;# # of observations in set 1
-      echo "1000000.0"    >> $COSD ;# error variance for set 1, observation 1
-      echo "1"            >> $COSD ;# 1 == state variable 1
+      echo "10"            > $COS  ;# upper bound on number of observations in sequence
+      echo "0"            >> $COS  ;# number of copies of data (0 for just a definition)
+      echo "0"            >> $COS  ;# number of quality control values per field
+      echo "1"            >> $COS  ;# anything (but -1) to continue
+      echo "-1"           >> $COS  ;# -1 == state variable 1     ------------
+      echo "1 0"          >> $COS  ;# first obs time (days, seconds)        |
+      echo "1000000.0"    >> $COS  ;# error variance for this observation   |
+      echo "-1"           >> $COS  ;# -1 == no more observations ------------
+      echo "set_def.out"  >> $COS  ;# output file name
 
-      echo "set_def.out"   > $COS  ;# same filename as 'output' above
-      echo "1"            >> $COS  ;# make a "regular" sequence
-      echo "10000"        >> $COS  ;# number of observations in first set
-      echo "1 0"          >> $COS  ;# time of first obs (days, seconds)
-      echo "1 0"          >> $COS  ;# observation interval (days, seconds)
-      echo "obs_seq.in"   >> $COS  ;# output file name -- destined for perfect_model_obs 
+      echo "set_def.out"   > $CFN  ;# same filename as 'output' above
+      echo "1"            >> $CFN  ;# make a "regular" sequence
+      echo "10000"        >> $CFN  ;# number of observations in first set
+      echo "1 0"          >> $CFN  ;# time of first obs (days, seconds)
+      echo "1 0"          >> $CFN  ;# observation interval (days, seconds)
+      echo "obs_seq.in"   >> $CFN  ;# output file -- destined for perfect_model_obs 
 
       echo "&model_nml"                         > model.nml
       echo "   g = 8.0,"                       >> model.nml
@@ -150,18 +158,22 @@ switch ( ${Model} )
 
    case lorenz_96:
 
-      echo "set_def.out"   > $COSD ;# output file name
-      echo "1"            >> $COSD ;# # of unique observation SETS to define
-      echo "1"            >> $COSD ;# # of observations in set 1
-      echo "1000000.0"    >> $COSD ;# error variance for set 1, observation 1
-      echo "1"            >> $COSD ;# 1 == state variable 1
+      echo "10"            > $COS  ;# upper bound on number of observations in sequence
+      echo "0"            >> $COS  ;# number of copies of data (0 for just a definition)
+      echo "0"            >> $COS  ;# number of quality control values per field
+      echo "1"            >> $COS  ;# anything (but -1) to continue
+      echo "-1"           >> $COS  ;# -1 == state variable 1     ------------
+      echo "1 0"          >> $COS  ;# first obs time (days, seconds)        |
+      echo "1000000.0"    >> $COS  ;# error variance for this observation   |
+      echo "-1"           >> $COS  ;# -1 == no more observations ------------
+      echo "set_def.out"  >> $COS  ;# output file name
 
-      echo "set_def.out"   > $COS  ;# same filename as 'output' above
-      echo "1"            >> $COS  ;# make a "regular" sequence
-      echo "1000"         >> $COS  ;# number of observations in first set
-      echo "1 0"          >> $COS  ;# time of first obs (days, seconds)
-      echo "1 0"          >> $COS  ;# observation interval (days, seconds)
-      echo "obs_seq.in"   >> $COS  ;# output file name -- destined for perfect_model_obs
+      echo "set_def.out"   > $CFN  ;# same filename as 'output' above
+      echo "1"            >> $CFN  ;# make a "regular" sequence
+      echo "1000"         >> $CFN  ;# number of observations in first set
+      echo "1 0"          >> $CFN  ;# time of first obs (days, seconds)
+      echo "1 0"          >> $CFN  ;# observation interval (days, seconds)
+      echo "obs_seq.in"   >> $CFN  ;# output file -- destined for perfect_model_obs
 
       echo "&model_nml"              > model.nml
       echo "   model_size = 40,"    >> model.nml
@@ -172,22 +184,59 @@ switch ( ${Model} )
 
    breaksw
 
+   case lorenz_96_2scale:
+
+      echo "10"            > $COS  ;# upper bound on number of observations in sequence
+      echo "0"            >> $COS  ;# number of copies of data (0 for just a definition)
+      echo "0"            >> $COS  ;# number of quality control values per field
+      echo "1"            >> $COS  ;# anything (but -1) to continue
+      echo "-1"           >> $COS  ;# -1 == state variable 1     ------------
+      echo "1 0"          >> $COS  ;# first obs time (days, seconds)        |
+      echo "1000000.0"    >> $COS  ;# error variance for this observation   |
+      echo "-1"           >> $COS  ;# -1 == no more observations ------------
+      echo "set_def.out"  >> $COS  ;# output file name
+
+      echo "set_def.out"   > $CFN  ;# same filename as 'output' above
+      echo "1"            >> $CFN  ;# make a "regular" sequence
+      echo "1000"         >> $CFN  ;# number of observations in first set
+      echo "1 0"          >> $CFN  ;# time of first obs (days, seconds)
+      echo "1 0"          >> $CFN  ;# observation interval (days, seconds)
+      echo "obs_seq.in"   >> $CFN  ;# output file -- destined for perfect_model_obs
+
+      echo "&model_nml"               > model.nml
+      echo "   model_size_x = 36,"   >> model.nml
+      echo "   y_per_x = 10,"        >> model.nml
+      echo "   forcing = 10.00,"     >> model.nml
+      echo "   delta_t = 0.005,"     >> model.nml
+      echo "   coupling_b = 10.0,"   >> model.nml
+      echo "   coupling_c = 10.0,"   >> model.nml
+      echo "   coupling_h =  1.0,"   >> model.nml
+      echo "   local_y = .false.  /" >> model.nml
+
+      set num_ens_members = 100
+
+   breaksw
+
    case pe2lyr:
 
       set BINARY_RESTART_FILES = .true.
 
-      echo "set_def.out"   > $COSD ;# output file name
-      echo "1"            >> $COSD ;# # of unique observation SETS to define
-      echo "1"            >> $COSD ;# # of observations in set 1
-      echo "1000000.0"    >> $COSD ;# error variance for set 1, observation 1
-      echo "1"            >> $COSD ;# observe state variable #1
+      echo "10"            > $COS  ;# upper bound on number of observations in sequence
+      echo "0"            >> $COS  ;# number of copies of data (0 for just a definition)
+      echo "0"            >> $COS  ;# number of quality control values per field
+      echo "1"            >> $COS  ;# anything (but -1) to continue
+      echo "-1"           >> $COS  ;# -1 == state variable 1     ------------
+      echo "1 0"          >> $COS  ;# first obs time (days, seconds)        |
+      echo "1000000.0"    >> $COS  ;# error variance for this observation   |
+      echo "-1"           >> $COS  ;# -1 == no more observations ------------
+      echo "set_def.out"  >> $COS  ;# output file name
 
-      echo "set_def.out"   > $COS  ;# same filename as 'output' above
-      echo "1"            >> $COS  ;# make a "regular" sequence
-      echo "100"          >> $COS  ;# # of observations
-      echo "1 0"          >> $COS  ;# first obs time (days, seconds)
-      echo "1 0"          >> $COS  ;# observation interval (d, s)
-      echo "obs_seq.in"   >> $COS  ;# output file name -- destined for perfect_model_obs
+      echo "set_def.out"   > $CFN  ;# same filename as 'output' above
+      echo "1"            >> $CFN  ;# make a "regular" sequence
+      echo "100"          >> $CFN  ;# # of observations
+      echo "1 0"          >> $CFN  ;# first obs time (days, seconds)
+      echo "1 0"          >> $CFN  ;# observation interval (d, s)
+      echo "obs_seq.in"   >> $CFN  ;# output file -- destined for perfect_model_obs
 
       echo " " > model.nml
 
@@ -197,18 +246,22 @@ switch ( ${Model} )
 
    default:     # lorenz_63, lorenz_84
 
-      echo "set_def.out"                                             > $COSD 
-      echo "1           ;# # of unique observation SETS to define"  >> $COSD
-      echo "1           ;# # of observations in set 1"              >> $COSD
-      echo "1000000.0   ;# error variance for set 1, observation 1" >> $COSD
-      echo "1           ;# 1 == state variable 1"                   >> $COSD
+      echo "10"            > $COS  ;# upper bound on number of observations in sequence
+      echo "0"            >> $COS  ;# number of copies of data (0 for just a definition)
+      echo "0"            >> $COS  ;# number of quality control values per field
+      echo "1"            >> $COS  ;# anything (but -1) to continue
+      echo "-1"           >> $COS  ;# -1 == state variable 1     ------------
+      echo "1 0"          >> $COS  ;# first obs time (days, seconds)        |
+      echo "1000000.0"    >> $COS  ;# error variance for this observation   |
+      echo "-1"           >> $COS  ;# -1 == no more observations ------------
+      echo "set_def.out"  >> $COS  ;# output file name
 
-      echo "set_def.out"   > $COS  ;# same filename as 'output' above
-      echo "1"            >> $COS  ;# make a "regular" sequence
-      echo "1000"         >> $COS  ;# # of observations
-      echo "1 0"          >> $COS  ;# first obs time (days, seconds)
-      echo "1 0"          >> $COS  ;# observation interval (d, s)
-      echo "obs_seq.in"   >> $COS  ;# output file name -- destined for perfect_model_obs
+      echo "set_def.out"   > $CFN  ;# same filename as 'output' above
+      echo "1"            >> $CFN  ;# make a "regular" sequence
+      echo "1000"         >> $CFN  ;# # of observations
+      echo "1 0"          >> $CFN  ;# first obs time (days, seconds)
+      echo "1 0"          >> $CFN  ;# observation interval (d, s)
+      echo "obs_seq.in"   >> $CFN  ;# output name -- destined for perfect_model_obs
 
       echo "&model_nml"          > model.nml
       echo "   deltat = 0.01 /" >> model.nml
@@ -227,44 +280,44 @@ echo "&assim_model_nml"                                   > assim_mod.nml
 echo "   binary_restart_files = $BINARY_RESTART_FILES /" >> assim_mod.nml
 
 echo "#----------------------------------------------------------------------"
-echo "Step 1.1: Create an observation SET definition."
+echo "Step 1.1: Create an observation definition."
 echo "#----------------------------------------------------------------------"
 
 echo '&utilities_nml'                                 > utilities.nml
-echo '   logfilename = "create_obs_set_def.out",'    >> utilities.nml
+echo '   logfilename = "create_obs_sequence.out",'   >> utilities.nml
 echo '   TERMLEVEL = 1 /'                            >> utilities.nml
-
-cat utilities.nml assim_mod.nml > input.nml
-
-./create_obs_set_def < $COSD
-
-if ( $status > 0 ) then
-   echo "ERROR: running create_obs_set_def bombed ..."
-   exit
-else
-   echo " "
-   echo "create_obs_set_def terminated normally"
-   echo " "
-endif
-
-echo "#----------------------------------------------------------------------"
-echo "# Step 1.2: Create an observation SEQUENCE definition (with nothing in them)"
-echo "#----------------------------------------------------------------------"
-
-echo '&utilities_nml'                                  > utilities.nml
-echo '   logfilename = "create_obs_sequence.out",'    >> utilities.nml
-echo '   TERMLEVEL = 1 /'                             >> utilities.nml
 
 cat utilities.nml assim_mod.nml > input.nml
 
 ./create_obs_sequence < $COS
 
 if ( $status > 0 ) then
-   echo "ERROR: create_obs_sequence bombed ..."
+   echo "ERROR: running create_obs_sequence bombed ..."
    exit
 else
    echo " "
    echo "create_obs_sequence terminated normally"
+   echo " "
+endif
+
+echo "#----------------------------------------------------------------------"
+echo "# Step 1.2: Create a fixed network definition (with nothing in them)"
+echo "#----------------------------------------------------------------------"
+
+echo '&utilities_nml'                                    > utilities.nml
+echo '   logfilename = "create_fixed_network_seq.out",' >> utilities.nml
+echo '   TERMLEVEL = 1 /'                               >> utilities.nml
+
+cat utilities.nml assim_mod.nml > input.nml
+
+./create_fixed_network_seq < $CFN
+
+if ( $status > 0 ) then
+   echo "ERROR: create_fixed_network_seq bombed ..."
+   exit
+else
+   echo " "
+   echo "create_fixed_network_seq terminated normally"
    echo " "
 endif
 
@@ -327,8 +380,7 @@ echo "#----------------------------------------------------------------------"
 
 echo '&utilities_nml'                                > utilities.nml
 echo '   logfilename = "perfect_model_obs.out",'    >> utilities.nml
-echo '   TERMLEVEL = 1'                             >> utilities.nml
-echo '&end'                                         >> utilities.nml
+echo '   TERMLEVEL = 1  /'                          >> utilities.nml
 
 cat << ENDofTask02 > perfect.nml
 &perfect_model_obs_nml
@@ -362,9 +414,8 @@ echo "# Step 2.2: Generate a set of ensemble initial conditions"
 echo "#----------------------------------------------------------------------"
 
 echo '&utilities_nml'                      > utilities.nml
-echo '   logfilename = "logfile.out",'    >> utilities.nml
-echo '   TERMLEVEL = 1'                   >> utilities.nml
-echo '&end'                               >> utilities.nml
+echo '   logfilename = "dart_log.out",'   >> utilities.nml
+echo '   TERMLEVEL = 1  /'                >> utilities.nml
 
 cat << ENDofTask03 > filter.nml
 &filter_nml
@@ -374,13 +425,16 @@ cat << ENDofTask03 > filter.nml
    cov_inflate = 1.00,
    start_from_restart = .false.,
    output_restart = .true.
-   obs_sequence_file_name = "obs_seq.out",
+   obs_sequence_in_name = "obs_seq.out",
+   obs_sequence_out_name = "obs_seq.final",
    restart_in_file_name = "perfect_ics",
    restart_out_file_name = "filter_restart",
    init_time_days = 0,
    init_time_seconds = 0, 
    output_state_ens_mean = .true.,
    output_state_ens_spread = .true.,
+   output_obs_ens_mean = .true.,
+   output_obs_ens_spread = .true.,
    num_output_ens_members = 0,
    output_interval = 1       /
 ENDofTask03
@@ -407,12 +461,12 @@ else
    echo " "
    echo "filter terminated normally"
    echo " "
-   \rm -f input*default utilities.nml perfect.nml model.nml assim_mod.nml filter.nml 
-   \rm -f set_def.out create_obs_set_def.in create_obs_sequence.in obs_seq.in
+   \rm -f utilities.nml perfect.nml model.nml assim_mod.nml filter.nml 
+   \rm -f set_def.out obs_seq.in ${COS} ${CFN}
 endif
 
 mv perfect_restart perfect_ics
-mv filter_restart filter_ics
+mv  filter_restart  filter_ics
 
 #======================================================================
 # Restore the existing namelists ...
diff --git a/shell_scripts/RunL63 b/shell_scripts/RunL63
--- a/shell_scripts/RunL63
+++ b/shell_scripts/RunL63
@@ -116,9 +116,9 @@ set SAVEME = .NamelistStorage.$$
 if ( ! -d $SAVEME ) then
    mkdir ${SAVEME}
 endif
-foreach FILE ( *.nml *default )
-   \mv -f $FILE ${SAVEME}
-end
+\mv -f *.nml         ${SAVEME}
+\mv -f *.nml_default ${SAVEME}
+
 echo 'Saved all existing *.nml into directory '"$SAVEME"
 echo 'Will restore and remove the directory at the end.'
 
@@ -126,21 +126,25 @@ echo 'Will restore and remove the directory at the end.'
 # Create the executables if they do not exist.
 #======================================================================
 
-if !( -e create_obs_set_def ) then
-   csh mkmf_create_obs_set_def
-   make || exit 1
-endif
 if !( -e create_obs_sequence ) then
    csh mkmf_create_obs_sequence
+   make || exit 1
+   \rm -f input.nml.create_obs_sequence_default 
+endif
+if !( -e create_fixed_network_seq ) then
+   csh mkmf_create_fixed_network_seq
    make || exit 2
+   \rm -f input.nml.create_fixed_network_seq_default
 endif
 if !( -e perfect_model_obs ) then
    csh mkmf_perfect_model_obs
    make || exit 3
+   \rm -f input.nml.perfect_model_obs_default
 endif
 if !( -e filter ) then
    csh mkmf_filter
    make || exit 4
+   \rm -f input.nml.filter_default
 endif
 \rm -f *.o *.d *.mod Makefile
 
@@ -148,15 +152,9 @@ endif
 # Create common namelists -- lots of ways to do it.
 #======================================================================
 
-cat << ENDofTask00 > utilities.nml
-&utilities_nml
-   logfilename = "create_obs_set_def.out",
-   TERMLEVEL = 1 /
-ENDofTask00
-   
 cat << ENDofTask01 > assim_mod.nml
 &assim_model_nml
-   binary_restart_files = .true. /
+   binary_restart_files = .false. /
 ENDofTask01
 
 cat << ENDofTask02 > model.nml
@@ -175,30 +173,40 @@ ENDofTask02
 #======================================================================
 
 echo " "
-echo "Running create_obs_set_def ..."
+echo "Running create_obs_sequence ..."
 echo " "
 
+set COS = create_obs_sequence.in
 
-echo "set_def.out"          > create_obs_set_def.in ;# output file name
-echo "1"                   >> create_obs_set_def.in ;# # of unique observation sets
-echo "3"                   >> create_obs_set_def.in ;# # of observations in set 1 (x,y,z)
-echo $obs_error_variance   >> create_obs_set_def.in ;# error variance for set 1, obs 1
-echo "1"                   >> create_obs_set_def.in ;# 1 == state variable 1 (X)
-echo $obs_error_variance   >> create_obs_set_def.in ;# error variance for set 1, obs 2
-echo "2"                   >> create_obs_set_def.in ;# 2 == state variable 2 (Y)
-echo $obs_error_variance   >> create_obs_set_def.in ;# error variance for set 1, obs 3
-echo "3"                   >> create_obs_set_def.in ;# 3 == state variable 3 (Z)
+echo "4"                   > $COS  ;# upper bound on number of observations in sequence
+echo "0"                  >> $COS  ;# number of copies of data (0 for just a definition)
+echo "0"                  >> $COS  ;# number of quality control values per field
+echo "1"                  >> $COS  ;# anything (but -1) to continue ---------
+echo "-1"                 >> $COS  ;# -1 == state variable 1                |
+echo "0 0"                >> $COS  ;# obs time (days, seconds)              |
+echo $obs_error_variance  >> $COS  ;# error variance for set 1, obs 1       |
+echo "1"                  >> $COS  ;# -1 == no more observations ------------
+echo "-2"                 >> $COS  ;# -2 == state variable 2                |
+echo "0 0"                >> $COS  ;# obs time (days, seconds)              |
+echo $obs_error_variance  >> $COS  ;# error variance                        |
+echo "1"                  >> $COS  ;# -1 == no more observations ------------
+echo "-3"                 >> $COS  ;# -1 == state variable 1                |
+echo "0 0"                >> $COS  ;# obs time (days, seconds)              |
+echo $obs_error_variance  >> $COS  ;# error variance                        |
+echo "-1"                 >> $COS  ;# -1 == no more observations ------------
+echo "set_def.out"        >> $COS  ;# output file name
+
 
 echo '&utilities_nml'                                  > utilities.nml
-echo '   logfilename = "create_obs_set_def.out"'      >> utilities.nml
+echo '   logfilename = "create_obs_sequence.out"'     >> utilities.nml
 echo '   TERMLEVEL = 1   /'                           >> utilities.nml
 
 cat utilities.nml assim_mod.nml model.nml > input.nml
 
-./create_obs_set_def < create_obs_set_def.in
+./create_obs_sequence < $COS
 
 if ( $status > 0 ) then
-   echo "ERROR: running create_obs_set_def bombed ..."
+   echo "ERROR: running create_obs_sequence bombed ..."
    exit
 endif
 
@@ -208,27 +216,28 @@ endif
 #======================================================================
 
 echo " "
-echo "Running create_obs_sequence ..."
+echo "Running create_fixed_network_seq ..."
 echo " "
 
+set CFN = create_fixed_network_seq.in
 
-echo "set_def.out"            > create_obs_sequence.in ;# same filename as 'output' above
-echo "1"                     >> create_obs_sequence.in ;# make a "regular" sequence
-echo $num_obs                >> create_obs_sequence.in ;# number of observations in set 1
-echo $ob_day_1 $ob_seconds_1 >> create_obs_sequence.in ;# time of first observation
-echo $ob_day_1 $ob_seconds_1 >> create_obs_sequence.in ;# observation interval
-echo "obs_seq.in"            >> create_obs_sequence.in ;# output file name -- destined for perfect_model_obs
+echo "set_def.out"            > $CFN ;# same filename as 'output' above
+echo "1"                     >> $CFN ;# make a "regular" sequence
+echo $num_obs                >> $CFN ;# number of observations in set 1
+echo $ob_day_1 $ob_seconds_1 >> $CFN ;# time of first observation
+echo $ob_day_1 $ob_seconds_1 >> $CFN ;# observation interval
+echo "obs_seq.in"            >> $CFN ;# output file name -- destined for perfect_model_obs
  
-echo '&utilities_nml'                              > utilities.nml
-echo '   logfilename = "create_obs_sequence.out"' >> utilities.nml
-echo '   TERMLEVEL = 1   /'                       >> utilities.nml
+echo '&utilities_nml'                                   > utilities.nml
+echo '   logfilename = "create_fixed_network_seq.out"' >> utilities.nml
+echo '   TERMLEVEL = 1   /'                            >> utilities.nml
 
 cat utilities.nml assim_mod.nml model.nml > input.nml
 
-./create_obs_sequence < create_obs_sequence.in
+./create_fixed_network_seq < $CFN
 
 if ( $status > 0 ) then
-   echo "ERROR: create_obs_sequence bombed ..."
+   echo "ERROR: create_fixed_network_seq bombed ..."
    exit
 endif
 
@@ -290,14 +299,18 @@ set async = 0
 set ens_size = $NumEns
 set start_from_restart = .true.
 set output_restart = .true.
-set obs_sequence_file_name = '"obs_seq.out"'
+set obs_sequence_in_name = '"obs_seq.out"'
+set obs_sequence_out_name = '"obs_seq.final"'
 set restart_in_file_name = '"filter_ics"'
 set restart_out_file_name = '"filter_restart"'
 set init_time_days = 0
 set init_time_seconds = 0
 set output_state_ens_mean = .true.
 set output_state_ens_spread = .true.
-set num_output_ens_members = $NumEns
+set output_obs_ens_mean = .true.
+set output_obs_ens_spread = .true.
+set num_output_state_members = $NumEns
+set num_output_obs_members = $NumEns
 set output_interval = 1
 
 
@@ -305,24 +318,28 @@ echo '&utilities_nml'                            > utilities.nml
 echo '   logfilename = "filter.out"'            >> utilities.nml
 echo '   TERMLEVEL = 1   /'                     >> utilities.nml
 
-echo " "                                                        > filter.nml
-echo "&filter_nml"                                             >> filter.nml
-echo "   async = $async ,"                                     >> filter.nml
-echo "   ens_size = $ens_size ,"                               >> filter.nml
-echo "   cutoff = $cutoff ,"                                   >> filter.nml
-echo "   cov_inflate = $cov_inflate ,"                         >> filter.nml
-echo "   start_from_restart = $start_from_restart ,"           >> filter.nml
-echo "   output_restart = $output_restart ,"                   >> filter.nml
-echo "   obs_sequence_file_name = $obs_sequence_file_name ,"   >> filter.nml
-echo "   restart_in_file_name = $restart_in_file_name ,"       >> filter.nml
-echo "   restart_out_file_name = $restart_out_file_name ,"     >> filter.nml
-echo "   init_time_days = $init_time_days ,"                   >> filter.nml
-echo "   init_time_seconds = $init_time_seconds ,"             >> filter.nml
-echo "   output_state_ens_mean = $output_state_ens_mean ,"     >> filter.nml
-echo "   output_state_ens_spread = $output_state_ens_spread ," >> filter.nml
-echo "   num_output_ens_members = $num_output_ens_members ,"   >> filter.nml
-echo "   output_interval = $output_interval    /"              >> filter.nml
-echo " "                                                       >> filter.nml
+echo " "                                                          > filter.nml
+echo "&filter_nml"                                               >> filter.nml
+echo "   async = $async ,"                                       >> filter.nml
+echo "   ens_size = $ens_size ,"                                 >> filter.nml
+echo "   cutoff = $cutoff ,"                                     >> filter.nml
+echo "   cov_inflate = $cov_inflate ,"                           >> filter.nml
+echo "   start_from_restart = $start_from_restart ,"             >> filter.nml
+echo "   output_restart = $output_restart ,"                     >> filter.nml
+echo "   obs_sequence_in_name = $obs_sequence_in_name ,"         >> filter.nml
+echo "   obs_sequence_out_name = $obs_sequence_out_name ,"       >> filter.nml
+echo "   restart_in_file_name = $restart_in_file_name ,"         >> filter.nml
+echo "   restart_out_file_name = $restart_out_file_name ,"       >> filter.nml
+echo "   init_time_days = $init_time_days ,"                     >> filter.nml
+echo "   init_time_seconds = $init_time_seconds ,"               >> filter.nml
+echo "   output_state_ens_mean = $output_state_ens_mean ,"       >> filter.nml
+echo "   output_state_ens_spread = $output_state_ens_spread ,"   >> filter.nml
+echo "   output_obs_ens_mean = $output_obs_ens_mean ,"           >> filter.nml
+echo "   output_obs_ens_spread = $output_obs_ens_spread ,"       >> filter.nml
+echo "   num_output_state_members = $num_output_state_members ," >> filter.nml
+echo "   num_output_obs_members = $num_output_obs_members ,"     >> filter.nml
+echo "   output_interval = $output_interval    /"                >> filter.nml
+echo " "                                                         >> filter.nml
 
 cat utilities.nml assim_mod.nml model.nml filter.nml > input.nml
 
@@ -334,9 +351,8 @@ else
    echo " "
    echo "filter terminated normally"
    echo " "
-   \rm -f create_obs_set_def.in create_obs_sequence.in 
+   \rm -f $COS $CFN set_def.out
    \rm -f utilities.nml assim_mod.nml model.nml perfect.nml filter.nml input.nml
-   \rm -f set_def.out input.nml*default
 endif
 
 #======================================================================
diff --git a/shell_scripts/RunL96 b/shell_scripts/RunL96
--- a/shell_scripts/RunL96
+++ b/shell_scripts/RunL96
@@ -8,9 +8,9 @@
 #
 # script to run an experiment with existing intial conditions
 # Interesting case #1 (filter divergence)
-# N=20, inflate = 1.0, cutoff=1000000.0, 200x12hours
-# RERUN inflate = 1.05
-# RERUN inflate = 1.05, cutoff = 0.2
+# N=20, cov_inflate = 1.0, cutoff=1000000.0, 200x12hours
+# RERUN cov_inflate = 1.05
+# RERUN cov_inflate = 1.05, cutoff = 0.2
 #======================================================================
 # Find the project and build it, if need be.
 #======================================================================
@@ -120,9 +120,9 @@ set SAVEME = .NamelistStorage.$$
 if ( ! -d $SAVEME ) then
    mkdir ${SAVEME}
 endif
-foreach FILE ( *.nml *default )
-   \mv -f $FILE ${SAVEME}
-end
+\mv -f *.nml         ${SAVEME}
+\mv -f *.nml_default ${SAVEME}
+
 echo 'Saved all existing *.nml into directory '"$SAVEME"
 echo 'Will restore and remove the directory at the end.'
 
@@ -130,21 +130,25 @@ echo 'Will restore and remove the directory at the end.'
 # Create the executables if they do not exist.
 #======================================================================
 
-if !( -e create_obs_set_def ) then
-   csh mkmf_create_obs_set_def
-   make || exit 1
-endif
 if !( -e create_obs_sequence ) then
    csh mkmf_create_obs_sequence
+   make || exit 1
+   \rm -f input.nml.create_obs_sequence_default 
+endif
+if !( -e create_fixed_network_seq ) then
+   csh mkmf_create_fixed_network_seq
    make || exit 2
+   \rm -f input.nml.create_fixed_network_seq_default
 endif
 if !( -e perfect_model_obs ) then
    csh mkmf_perfect_model_obs
    make || exit 3
+   \rm -f input.nml.perfect_model_obs_default
 endif
 if !( -e filter ) then
    csh mkmf_filter
    make || exit 4
+   \rm -f input.nml.filter_default
 endif
 \rm -f *.o *.d *.mod Makefile
 
@@ -152,12 +156,6 @@ endif
 # Create common namelists -- lots of ways to do it.
 #======================================================================
 
-cat << ENDofTask00 > utilities.nml
-&utilities_nml
-   logfilename = "create_obs_set_def.out",
-   TERMLEVEL = 1 /
-ENDofTask00
-   
 cat << ENDofTask01 > assim_mod.nml
 &assim_model_nml
    binary_restart_files = .false. /
@@ -175,15 +173,19 @@ echo '   deltat = 0.005   /' >> model.nml
 #======================================================================
 
 echo " "
-echo "Running create_obs_set_def ..."
+echo "Running create_obs_sequence ..."
 echo " "
+
+echo '&utilities_nml'                                   > utilities.nml
+echo '   logfilename = "create_obs_sequence.out"'      >> utilities.nml
+echo '   TERMLEVEL = 1   /'                            >> utilities.nml
 
 cat utilities.nml assim_mod.nml model.nml > input.nml
 
-./create_obs_set_def < ../random_obs.input
+./create_obs_sequence < ../random_obs.input
 
 if ( $status > 0 ) then
-   echo "ERROR: running create_obs_set_def bombed ..."
+   echo "ERROR: running create_obs_sequence bombed ..."
    exit
 endif
 
@@ -193,27 +195,28 @@ endif
 #======================================================================
 
 echo " "
-echo "Running create_obs_sequence ..."
+echo "Running create_fixed_network_seq ..."
 echo " "
 
+set CFN = create_fixed_network_seq.in
 
-echo "set_def.out"            > create_obs_sequence.in ;# same filename as 'output' above
-echo "1"                     >> create_obs_sequence.in ;# make a "regular" sequence
-echo $num_obs                >> create_obs_sequence.in ;# number of observations in set 1
-echo $ob_day_1 $ob_seconds_1 >> create_obs_sequence.in ;# time of first observation
-echo $ob_day_1 $ob_seconds_1 >> create_obs_sequence.in ;# observation interval
-echo "obs_seq.in"            >> create_obs_sequence.in ;# output file name -- destined for perfect_model_obs
+echo "set_def.out"            > $CFN ;# same filename as 'output' above
+echo "1"                     >> $CFN ;# make a "regular" sequence
+echo $num_obs                >> $CFN ;# number of observations in set 1
+echo $ob_day_1 $ob_seconds_1 >> $CFN ;# time of first observation
+echo $ob_day_1 $ob_seconds_1 >> $CFN ;# observation interval
+echo "obs_seq.in"            >> $CFN ;# output file name -- destined for perfect_model_obs
  
-echo '&utilities_nml'                              > utilities.nml
-echo '   logfilename = "create_obs_sequence.out"' >> utilities.nml
-echo '   TERMLEVEL = 1   /'                       >> utilities.nml
+echo '&utilities_nml'                                   > utilities.nml
+echo '   logfilename = "create_fixed_network_seq.out"' >> utilities.nml
+echo '   TERMLEVEL = 1   /'                            >> utilities.nml
 
 cat utilities.nml assim_mod.nml model.nml > input.nml
 
-./create_obs_sequence < create_obs_sequence.in
+./create_fixed_network_seq < $CFN
 
 if ( $status > 0 ) then
-   echo "ERROR: create_obs_sequence bombed ..."
+   echo "ERROR: create_fixed_network_seq bombed ..."
    exit
 endif
 
@@ -275,14 +278,18 @@ set async = 0
 set ens_size = $NumEns
 set start_from_restart = .true.
 set output_restart = .true.
-set obs_sequence_file_name = '"obs_seq.out"'
+set obs_sequence_in_name = '"obs_seq.out"'
+set obs_sequence_out_name = '"obs_seq.final"'
 set restart_in_file_name = '"filter_ics"'
 set restart_out_file_name = '"filter_restart"'
 set init_time_days = 0
 set init_time_seconds = 0
 set output_state_ens_mean = .true.
 set output_state_ens_spread = .true.
-set num_output_ens_members = $NumEns
+set output_obs_ens_mean = .true.
+set output_obs_ens_spread = .true.
+set num_output_state_members = $NumEns
+set num_output_obs_members = $NumEns
 set output_interval = 1
 
 
@@ -290,24 +297,28 @@ echo '&utilities_nml'                            > utilities.nml
 echo '   logfilename = "filter.out"'            >> utilities.nml
 echo '   TERMLEVEL = 1   /'                     >> utilities.nml
 
-echo " "                                                        > filter.nml
-echo "&filter_nml"                                             >> filter.nml
-echo "   async = $async ,"                                     >> filter.nml
-echo "   ens_size = $ens_size ,"                               >> filter.nml
-echo "   cutoff = $cutoff ,"                                   >> filter.nml
-echo "   cov_inflate = $cov_inflate ,"                         >> filter.nml
-echo "   start_from_restart = $start_from_restart ,"           >> filter.nml
-echo "   output_restart = $output_restart ,"                   >> filter.nml
-echo "   obs_sequence_file_name = $obs_sequence_file_name ,"   >> filter.nml
-echo "   restart_in_file_name = $restart_in_file_name ,"       >> filter.nml
-echo "   restart_out_file_name = $restart_out_file_name ,"     >> filter.nml
-echo "   init_time_days = $init_time_days ,"                   >> filter.nml
-echo "   init_time_seconds = $init_time_seconds ,"             >> filter.nml
-echo "   output_state_ens_mean = $output_state_ens_mean ,"     >> filter.nml
-echo "   output_state_ens_spread = $output_state_ens_spread ," >> filter.nml
-echo "   num_output_ens_members = $num_output_ens_members ,"   >> filter.nml
-echo "   output_interval = $output_interval    /"              >> filter.nml
-echo " "                                                       >> filter.nml
+echo " "                                                          > filter.nml
+echo "&filter_nml"                                               >> filter.nml
+echo "   async = $async ,"                                       >> filter.nml
+echo "   ens_size = $ens_size ,"                                 >> filter.nml
+echo "   cutoff = $cutoff ,"                                     >> filter.nml
+echo "   cov_inflate = $cov_inflate ,"                           >> filter.nml
+echo "   start_from_restart = $start_from_restart ,"             >> filter.nml
+echo "   output_restart = $output_restart ,"                     >> filter.nml
+echo "   obs_sequence_in_name = $obs_sequence_in_name ,"         >> filter.nml
+echo "   obs_sequence_out_name = $obs_sequence_out_name ,"       >> filter.nml
+echo "   restart_in_file_name = $restart_in_file_name ,"         >> filter.nml
+echo "   restart_out_file_name = $restart_out_file_name ,"       >> filter.nml
+echo "   init_time_days = $init_time_days ,"                     >> filter.nml
+echo "   init_time_seconds = $init_time_seconds ,"               >> filter.nml
+echo "   output_state_ens_mean = $output_state_ens_mean ,"       >> filter.nml
+echo "   output_state_ens_spread = $output_state_ens_spread ,"   >> filter.nml
+echo "   output_obs_ens_mean = $output_obs_ens_mean ,"           >> filter.nml
+echo "   output_obs_ens_spread = $output_obs_ens_spread ,"       >> filter.nml
+echo "   num_output_state_members = $num_output_state_members ," >> filter.nml
+echo "   num_output_obs_members = $num_output_obs_members ,"     >> filter.nml
+echo "   output_interval = $output_interval    /"                >> filter.nml
+echo " "                                                         >> filter.nml
 
 cat utilities.nml assim_mod.nml model.nml filter.nml > input.nml
 
@@ -319,9 +330,8 @@ else
    echo " "
    echo "filter terminated normally"
    echo " "
-   \rm -f create_obs_set_def.in create_obs_sequence.in 
+   \rm -f $CFN set_def.out
    \rm -f utilities.nml assim_mod.nml model.nml perfect.nml filter.nml input.nml
-   \rm -f set_def.out input.nml*default
 endif
 
 #======================================================================
diff --git a/shell_scripts/RunPE2 b/shell_scripts/RunPE2
--- a/shell_scripts/RunPE2
+++ b/shell_scripts/RunPE2
@@ -6,45 +6,37 @@
 #
 # $Id$
 #
-# This script will do one of two things -- based on an envir
+# script to run an experiment with existing intial conditions
+#======================================================================
+# Find the project and build it, if need be.
+#======================================================================
 
 set SNAME = $0
+set clobber
+set DART_HOME = ~/DART
+set Model = pe2lyr
 
 switch ($#argv) 
-   case 0:
-      #===================================================================
-      # With no arguments -- running with the default observation sequence  
-      # supplied by Jeff Whitaker -- 151 days with 362 obs per day.
-      # The initial conditions files are ASCII ...
-      #===================================================================
-      set pe2lyr_case = 1
-   breaksw
-
    case 1:
-      #===================================================================
-      # If the solo argument is 
-      # 1       -- running with the default observation sequence  (case 0)
-      # <other> -- running from a prescribed set of BINARY initial 
-      #            conditions as created in the script MakeICs and with a
-      #            short observation sequence and just a few ensemble mems.
-      #===================================================================
       set pe2lyr_case = $1
+   case 2:
    breaksw
-
+      set pe2lyr_case = $1
+      set DART_HOME = $2
+      breaksw
    default:
       echo " "
-      echo "usage: $SNAME:t [scenarionumber]"
+      echo "usage: $SNAME:t scenarionumber [DART_HOME]"
       echo " "
       echo "This script exercises the PE2LYR model."
-      echo "If 'scenarionumber' is absent -- the default behavior is to"
-      echo "run with the default observation sequence supplied by Jeff Whitaker "
-      echo "151 days with 362 obs per day."
       echo " "
       echo "If scenarionumber is '1' -- the default case is run."
+      echo "   i.e. the default observation sequence supplied by Jeff Whitaker "
+      echo "   151 days with 362 obs per day."
       echo " "
-      echo "If scenarionumber is anything else -- a prescribed set of BINARY initial conditions"
-      echo "is used as well as a short observation sequence with just a few ensemble"
-      echo "members used as well as a short observation sequence."
+      echo "If scenarionumber is anything else -- the same set of initial conditions"
+      echo "   is used as well as a short observation sequence with just a few"
+      echo "   ensemble members."
       echo " "
 
       @ MYSTATUS = 1
@@ -53,66 +45,116 @@ switch ($#argv)
 endsw
 
 #======================================================================
-# Find the project and build it, if need be.
+# Set defaults.
+# This is only meant to be illustrative.
+# It is ABSOLUTELY not comprehensive.
 #======================================================================
 
-set Model = pe2lyr
+set ens_size = 3
+set num_output_state_members = $ens_size
+set num_output_obs_members = $ens_size
+set async = 0
+set cutoff = 0.25
+set cov_inflate = 1.01
+set start_from_restart = .true.
+set output_restart = .true.
+set perfect_restart_in_file_name = '"perfect_ics"'
+set perfect_restart_out_file_name = '"perfect_restart"'
+set filter_restart_in_file_name = '"filter_ics"'
+set filter_restart_out_file_name = '"filter_restart"'
+set init_time_days = 0
+set init_time_seconds = 0
+set output_state_ens_mean = .true.
+set output_state_ens_spread = .true.
+set output_obs_ens_mean = .true.
+set output_obs_ens_spread = .true.
+set output_interval = 1
 
-if ( ${?DART_HOME} ) then
-   if ( -d $DART_HOME ) then
-      setenv DARTHOME $DART_HOME
-   else
-      echo "$DART_HOME does not exist on this platform"
-   endif
-else if ( -d /export/data/gsp/${USER}/DART ) then
-   setenv DARTHOME /export/data/gsp/${USER}/DART
-else if ( -d /data/gsp/${USER}/DART ) then
-   setenv DARTHOME /data/gsp/${USER}/DART
-else if ( -d /home/${USER}/DART ) then
-   setenv DARTHOME /home/${USER}/DART
-else
-   echo "no DART project"
-   exit
-endif
-echo "DART project directory is $DARTHOME"
-echo "       working with model $Model"
-sleep 2
+#======================================================================
+# check environment variables 'NumEns' 'CovInflate' and 'Cutoff'  
+# if they are not defined, use default values.
+# There is no checking for sensible values ... caveat emptor ...
 
-cd ${DARTHOME}/models/${Model}/work
+if ( ${?NumEns} ) then
+   set ens_size = $NumEns
+   set num_output_state_members = $NumEns
+   set num_output_obs_members = $NumEns
+endif
+if ( ${?CovInflate} ) then
+   set cov_inflate = $CovInflate
+endif
+if ( ${?Cutoff} ) then
+   set cutoff = $Cutoff
+endif
 
-if !( -e create_obs_set_def ) then
-   csh mkmf_create_obs_set_def
-   mv input.nml.mkmf default_create_obs_set_def.nml
-   make || exit 1
+#======================================================================
+# This block checks to see if workspace is viable.
+#======================================================================
+
+setenv DARTDIR ${DART_HOME}/models/${Model}/work
+if ( ! -d ${DARTDIR} ) then                                                     
+   echo "${DARTDIR} does not exist ... "
+   exit 2
 endif
-if !( -e create_obs_sequence ) then
-   csh mkmf_create_obs_sequence
-   mv input.nml.mkmf default_create_obs_sequence.nml
-   make || exit 1
-endif
-if !( -e perfect_model_obs ) then
-   csh mkmf_perfect_model_obs
-   mv input.nml.mkmf default_perfect_model_obs.nml
-   make || exit 1
-endif
-if !( -e filter ) then
-   csh mkmf_filter
-   mv input.nml.mkmf default_filter.nml
-   make || exit 1
-endif
-\rm -f *.o *.d *.mod Makefile
+
+echo "DART project directory is $DART_HOME"
+echo "Building Initial Conditions for $Model"
+echo "in directory $DARTDIR"
+echo "You have 4 seconds to stop this ..."
+sleep 1
+echo "3"
+sleep 1
+echo "2"
+sleep 1
+echo "1"
+sleep 1
+echo
+                                                                                
+cd ${DARTDIR}
 
 #======================================================================
 # Save any existing namelist ...
+# Creating a null namelist just to avoid moving nothing.
 #======================================================================
+
+touch nullnamelist$$.nml
+touch nullnamelist$$.nml_default
 
 set SAVEME = .NamelistStorage.$$
 if ( ! -d $SAVEME ) then
    mkdir ${SAVEME}
 endif
-foreach NAMELIST ( *.nml )
-   mv ${NAMELIST} ${SAVEME}
-end
+\mv -f *.nml         ${SAVEME}
+\mv -f *.nml_default ${SAVEME}
+
+echo 'Saved all existing *.nml into directory '"$SAVEME"
+echo 'Will restore and remove the directory at the end.'
+
+#======================================================================
+# Create the executables if they do not exist.
+#======================================================================
+
+if !( -e create_obs_sequence ) then
+   csh mkmf_create_obs_sequence
+   make || exit 1
+   \rm -f input.nml.create_obs_sequence_default 
+endif
+if !( -e create_fixed_network_seq ) then
+   csh mkmf_create_fixed_network_seq
+   make || exit 2
+   \rm -f input.nml.create_fixed_network_seq_default
+endif
+if !( -e perfect_model_obs ) then
+   csh mkmf_perfect_model_obs
+   make || exit 3
+   \rm -f input.nml.perfect_model_obs_default
+endif
+if !( -e filter ) then
+   csh mkmf_filter
+   make || exit 4
+   \rm -f input.nml.filter_default
+endif
+\rm -f *.o *.d *.mod Makefile
 
 #======================================================================
 # Simulate a particular observing system:
@@ -148,10 +190,13 @@ ENDofMessage
 
    cat JeffWhitakerREADME
 
-   set obs_sequence_in_name = '"obs_seq.in_151"'
-   set obs_sequence_file_name = '"obs_seq.out_151"'
    set ens_size = 50
-   set num_output_ens_members = 20
+   set num_output_state_members = 20
+   set num_output_obs_members = 20
+
+   set obs_sequence_in_name = obs_seq.in_151
+   set obs_sequence_out_name = obs_seq.out_151
+   set obs_sequence_final_name = obs_seq.final_151
 
    echo '&assim_model_nml'                     > assim_mod.nml
    echo '   binary_restart_files = .false. /' >> assim_mod.nml
@@ -159,90 +204,67 @@ ENDofMessage
 breaksw
 default:
 
-   set ens_size = 3
-   set num_output_ens_members = 3
+   set COS = create_obs_sequence.in
+   set CFN = create_fixed_network_seq.in
+   set obs_sequence_in_name = obs_seq.in
+   set obs_sequence_out_name = obs_seq.out
+   set obs_sequence_final_name = obs_seq.final
 
    echo " "
-   echo "Running create_obs_set_def ... just a few locations case"
+   echo "Running create_obs_sequence ... just a few locations case"
    echo "observation locations and error variances are entirely random."
    echo " "
 
-   echo "set_def.out"    > create_obs_set_def.in  ;# output filename
-   echo "1"             >> create_obs_set_def.in  ;# number of obs SETS
-   echo "2"             >> create_obs_set_def.in  ;# num obs in first set
-   echo "1.0"           >> create_obs_set_def.in  ;# error variance for first obs
-   echo "-1"            >> create_obs_set_def.in  ;# not a state variable
-   echo "-1"            >> create_obs_set_def.in  ;# surface observation
-   echo "23.0"          >> create_obs_set_def.in  ;# longitude [0,360]
-   echo "40.0"          >> create_obs_set_def.in  ;# latitude [-90,90]
-   echo "3"             >> create_obs_set_def.in  ;# obs kind: u = 1, v = 2, ps = 3, t = 4 q = 5
-   echo "1.0"           >> create_obs_set_def.in  ;# error variance for second obs
-   echo "-1"            >> create_obs_set_def.in  ;# not a state variable
-   echo "-1"            >> create_obs_set_def.in  ;# surface observation
-   echo "123.0"         >> create_obs_set_def.in  ;# longitude [0,360]
-   echo "-40.0"         >> create_obs_set_def.in  ;# latitude [-90,90]
-   echo "3"             >> create_obs_set_def.in  ;# obs kind: u = 1, v = 2, ps = 3, t = 4 q = 5
-
-   echo '&utilities_nml'                              > utilities.nml
-   echo '   logfilename = "create_obs_set_def.out",' >> utilities.nml
-   echo '   TERMLEVEL = 1 /'                         >> utilities.nml
-
-   echo '&assim_model_nml'                            > assim_mod.nml
-   echo '   binary_restart_files = .true. /'         >> assim_mod.nml
-
-   cat utilities.nml assim_mod.nml > input.nml
-
-   ./create_obs_set_def < create_obs_set_def.in
-
-   if ( $status > 0 ) then
-      echo "ERROR: running create_obs_set_def bombed ..."
-      exit
-   endif
-
-   echo "set_def.out"           > create_obs_sequence.in
-   echo "1"                    >> create_obs_sequence.in
-   echo "3"                    >> create_obs_sequence.in
-   echo "1 0"                  >> create_obs_sequence.in
-   echo "1 0"                  >> create_obs_sequence.in
-   echo "obs_seq.in"           >> create_obs_sequence.in
-
-   set obs_sequence_in_name = '"obs_seq.in"'
-   set obs_sequence_file_name = '"obs_seq.out"'
+   echo "10"             > $COS  ;# upper bound on number of observations in sequence
+   echo "0"             >> $COS  ;# number of copies of data (0 for just a definition)
+   echo "0"             >> $COS  ;# number of quality control values per field
+   echo "0"             >> $COS  ;# anything but -1 to continue
+   echo "-10"           >> $COS  ;# observing state variable #10
+   echo "0  0"          >> $COS  ;# at t = ( 0 0 ) ... (days  seconds)
+   echo "3"             >> $COS  ;# error variance
+   echo "-1"            >> $COS  ;# end of observation definition
+   echo "set_def.out"   >> $COS  ;# output filename
 
    echo '&utilities_nml'                               > utilities.nml
    echo '   logfilename = "create_obs_sequence.out",' >> utilities.nml
    echo '   TERMLEVEL = 1 /'                          >> utilities.nml
 
+   echo '&assim_model_nml'                             > assim_mod.nml
+   echo '   binary_restart_files = .false. /'         >> assim_mod.nml
+
    cat utilities.nml assim_mod.nml > input.nml
 
-   ./create_obs_sequence < create_obs_sequence.in
+   ./create_obs_sequence < $COS
 
    if ( $status > 0 ) then
       echo "ERROR: running create_obs_sequence bombed ..."
       exit
    endif
 
+   echo "set_def.out"            > $CFN ;# same filename as 'output' above
+   echo "1"                     >> $CFN ;# make a "regular" sequence
+   echo "10"                    >> $CFN ;# number of observations
+   echo "1 0"                   >> $CFN ;# time of first observation
+   echo "1 0"                   >> $CFN ;# observation interval
+   echo "$obs_sequence_in_name" >> $CFN ;# output file name -- destined for perfect_model_obs
+
+   echo '&utilities_nml'                                    > utilities.nml
+   echo '   logfilename = "create_fixed_network_seq.out",' >> utilities.nml
+   echo '   TERMLEVEL = 1 /'                               >> utilities.nml
+
+   cat utilities.nml assim_mod.nml > input.nml
+
+   ./create_fixed_network_seq < $CFN 
+
+   if ( $status > 0 ) then
+      echo "ERROR: running create_fixed_network_seq bombed ..."
+      exit
+   endif
+
+   \rm -f $COS $CFN 
+
 breaksw
 endsw
-
-#======================================================================
-# Create common namelists -- lots of ways to do it.
-#======================================================================
-
-set async = 0
-set cutoff = 0.25
-set cov_inflate = 1.01
-set start_from_restart = .true.
-set output_restart = .true.
-set perfect_restart_in_file_name = '"perfect_ics"'
-set perfect_restart_out_file_name = '"perfect_restart"'
-set filter_restart_in_file_name = '"filter_ics"'
-set filter_restart_out_file_name = '"filter_restart"'
-set init_time_days = 0
-set init_time_seconds = 0
-set output_state_ens_mean = .true.
-set output_state_ens_spread = .true.
-set output_interval = 1
 
 
 #======================================================================
@@ -257,8 +279,8 @@ echo " "
 
 echo "&perfect_model_obs_nml"                                       > perfect.nml
 echo "   async = $async ,"                                         >> perfect.nml
-echo "   obs_seq_in_file_name = $obs_sequence_in_name ,"           >> perfect.nml
-echo "   obs_seq_out_file_name = $obs_sequence_file_name ,"        >> perfect.nml
+echo '   obs_seq_in_file_name = "'$obs_sequence_in_name'" ,'       >> perfect.nml
+echo '   obs_seq_out_file_name = "'$obs_sequence_out_name'" ,'    >> perfect.nml
 echo "   start_from_restart = $start_from_restart ,"               >> perfect.nml
 echo "   output_restart = $output_restart ,"                       >> perfect.nml
 echo "   restart_in_file_name = $perfect_restart_in_file_name ,"   >> perfect.nml
@@ -269,14 +291,12 @@ echo "   output_interval = $output_interval /"                     >> perfect.nm
 
 echo '&utilities_nml'                              > utilities.nml
 echo '   logfilename = "perfect_obs.out"'         >> utilities.nml
-echo '   TERMLEVEL = 1 /'                         >> utilities.nml
+echo '   TERMLEVEL = 1  /'                        >> utilities.nml
 
 cat utilities.nml assim_mod.nml perfect.nml > input.nml
 
-cat input.nml
-
-#./perfect_model_obs
-
+./perfect_model_obs
+ 
 if ( $status > 0 ) then
    echo "ERROR: perfect_model_obs (synthetic) bombed ..."
    exit
@@ -298,25 +318,10 @@ echo " "
 echo "Running filter ..."
 echo " "
 
-#======================================================================
-# check environment variables 'NumEns' 'CovInflate' and 'Cutoff'  
-# if they are not defined, use default values.
-# There is no checking for sensible values ... caveat emptor ...
 
 echo "Ensemble size is $ens_size ..."
-echo "Num output ensemble members is $num_output_ens_members ..."
+echo "Num output (obs/state) members is $num_output_state_members ..."
 sleep 2
-
-if ( ${?NumEns} ) then
-   set ens_size = $NumEns
-   set num_output_ens_members = $NumEns
-endif
-if ( ${?CovInflate} ) then
-   set cov_inflate = $CovInflate
-endif
-if ( ${?Cutoff} ) then
-   set cutoff = $Cutoff
-endif
 
 echo '&utilities_nml'                            > utilities.nml
 echo '   logfilename = "filter.out"'            >> utilities.nml
@@ -330,14 +335,18 @@ echo "   cutoff = $cutoff ,"                                       >> filter.nml
 echo "   cov_inflate = $cov_inflate ,"                             >> filter.nml
 echo "   start_from_restart = $start_from_restart ,"               >> filter.nml
 echo "   output_restart = $output_restart ,"                       >> filter.nml
-echo "   obs_sequence_file_name = $obs_sequence_file_name ,"       >> filter.nml
+echo '   obs_sequence_in_name = "'$obs_sequence_out_name'" ,'      >> filter.nml
+echo '   obs_sequence_out_name = "'$obs_sequence_final_name'" ,'   >> filter.nml
 echo "   restart_in_file_name = $filter_restart_in_file_name ,"    >> filter.nml
 echo "   restart_out_file_name = $filter_restart_out_file_name ,"  >> filter.nml
 echo "   init_time_days = $init_time_days ,"                       >> filter.nml
 echo "   init_time_seconds = $init_time_seconds ,"                 >> filter.nml
 echo "   output_state_ens_mean = $output_state_ens_mean ,"         >> filter.nml
 echo "   output_state_ens_spread = $output_state_ens_spread ,"     >> filter.nml
-echo "   num_output_ens_members = $num_output_ens_members ,"       >> filter.nml
+echo "   output_obs_ens_mean = $output_obs_ens_mean ,"             >> filter.nml
+echo "   output_obs_ens_spread = $output_obs_ens_spread ,"         >> filter.nml
+echo "   num_output_state_members = $num_output_state_members ,"   >> filter.nml
+echo "   num_output_obs_members = $num_output_obs_members ,"       >> filter.nml
 echo "   output_interval = $output_interval /"                     >> filter.nml
 echo " "                                                           >> filter.nml
 
@@ -345,7 +354,7 @@ cat utilities.nml assim_mod.nml filter.nml > input.nml
 
 cat input.nml
 
-# ./filter
+./filter
 
 if ( $status > 0 ) then
    echo "ERROR: filter bombed ..."
@@ -353,19 +362,17 @@ else
    echo " "
    echo "filter terminated normally"
    echo " "
-   \rm -f create_obs_set_def.in create_obs_sequence.in 
    \rm -f utilities.nml assim_mod.nml perfect.nml filter.nml input.nml
+   \rm -f set_def.out input.nml*default
 endif
 
 #======================================================================
 # Restore the existing namelists ...
 #======================================================================
 
-foreach NAMELIST ( ${SAVEME}/*.nml )
-   mv ${NAMELIST} .
-end
+\mv -f ${SAVEME}/*.nml .
+\mv -f ${SAVEME}/*default .
 \rmdir ${SAVEME}
-
-\rm -f JeffWhitakerREADME
+\rm -f nullnamelist$$.nml nullnamelist$$.nml_default
 
 exit
