Adding support for CESM 1_2_1. Making minor changes to 1_1_1 to differentiate between the versions, now that multiple versions are supported.
git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/trunk@7244 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 9bfc3b8fe4ac0049cc9da8c303b231dc8b708b51

diff --git a/models/POP/shell_scripts/CESM1_2_1_setup_pmo b/models/POP/shell_scripts/CESM1_2_1_setup_pmo
--- a/models/POP/shell_scripts/CESM1_2_1_setup_pmo
+++ b/models/POP/shell_scripts/CESM1_2_1_setup_pmo
@@ -38,7 +38,7 @@
 # and start harvesting synthetic observations when CESM stops at 2004-02-01 06Z ...
 #
 # This script relies heavily on the information in:
-# http://www.cesm.ucar.edu/models/cesm1.1/cesm/doc/usersguide/book1.html
+# http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide1_2/book1.html
 #
 # ---------------------
 # How to use this script.
@@ -75,7 +75,7 @@
 # settings, it is safest to delete everything and start the run from scratch.
 # For the brave, read
 #
-# http://www.cesm.ucar.edu/models/cesm1.1/cesm/doc/usersguide/x1142.html
+# http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide1_2/x1080.html
 #
 # and you may be able to salvage something with
 # ./cesm_setup -clean
@@ -97,17 +97,17 @@
 # cesmtag       The version of the CESM source code to use when building the code.
 # ==============================================================================
 
-setenv case                 pop_1_1_1_pmo
+setenv case                 pop_1_2_1_pmo
 setenv compset              GIAF
 setenv resolution           T62_gx1v6
-setenv cesmtag              cesm1_1_1
+setenv cesmtag              cesm1_2_1
 
 # ==============================================================================
 # machines and directories:
 #
 # mach            Computer name
 # cesmroot        Location of the CESM code base.  This version of the script
-#                 only supports version cesm1_1_1.
+#                 only supports version cesm1_2_1.
 # caseroot        Will create the CESM case directory here, where the CESM+DART
 #                 configuration files will be stored.  This should probably not
 #                 be in scratch (on yellowstone, your 'work' partition is suggested).
@@ -356,6 +356,16 @@ cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
 
+# Check to make sure the land and atmosphere are 'data' components.
+
+if ( $?CLM_CONFIG_OPTS || $?CAM_DYCORE ) then
+   echo " "
+   echo "ERROR: This setup script is not appropriate for active land or atmosphere models."
+   echo "ERROR: Please use the models/CESM/shell_scripts examples for these cases."
+   echo " "
+   exit -3
+endif
+
 # MAX_TASKS_PER_NODE comes from $case/Tools/mkbatch.$machine
 @ ptile = $MAX_TASKS_PER_NODE / 2
 @ nthreads = 1
@@ -375,6 +385,7 @@ end
    @ cpl_tasks = $ptile
    @ glc_tasks = $ptile
    @ rof_tasks = $ptile
+   @ wav_tasks = $ptile
 
 # echo "task partitioning ... perhaps ... atm // ocn // lnd+ice+glc+rof"
 # presently, all components run 'serially' - one after another.
@@ -386,6 +397,7 @@ echo "OCN gets $ocn_tasks"
 echo "CPL gets $cpl_tasks"
 echo "GLC gets $glc_tasks"
 echo "ROF gets $rof_tasks"
+echo "WAV gets $wav_tasks"
 echo ""
 
 ./xmlchange NTHRDS_ATM=$nthreads,NTASKS_ATM=$atm_tasks,NINST_ATM=1
@@ -395,6 +407,7 @@ echo ""
 ./xmlchange NTHRDS_CPL=$nthreads,NTASKS_CPL=$cpl_tasks
 ./xmlchange NTHRDS_GLC=$nthreads,NTASKS_GLC=$glc_tasks,NINST_GLC=1
 ./xmlchange NTHRDS_ROF=$nthreads,NTASKS_ROF=$rof_tasks,NINST_ROF=1
+./xmlchange NTHRDS_WAV=$nthreads,NTASKS_WAV=$wav_tasks,NINST_WAV=1
 ./xmlchange ROOTPE_ATM=0
 ./xmlchange ROOTPE_LND=0
 ./xmlchange ROOTPE_ICE=0
@@ -402,8 +415,9 @@ echo ""
 ./xmlchange ROOTPE_CPL=0
 ./xmlchange ROOTPE_GLC=0
 ./xmlchange ROOTPE_ROF=0
+./xmlchange ROOTPE_WAV=0
 
-# http://www.cesm.ucar.edu/models/cesm1.1/cesm/doc/usersguide/c1158.html#run_start_stop
+# http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide1_2/c1096.html#run_start_stop
 # "A hybrid run indicates that CESM is initialized more like a startup, but uses
 # initialization datasets from a previous case. This is somewhat analogous to a
 # branch run with relaxed restart constraints. A hybrid run allows users to bring
@@ -459,11 +473,14 @@ endif
 # "In summary, users should ensure that the following is true,
 #  ATM_NCPL = LND_NCPL = ICE_NCPL >= ROF_NCPL >= OCN_NCPL"
 # ROF_NCPL defaults to $ATM_NCPL (24 in the default config)
-# OCN_NCPL defaults to 1 (per day)
+# OCN_NCPL and GLC_NCPL default to 1 (per day)
 #
-# OCN_NCPL == 4 sets the ocean coupling time to 6 hours.
 # OCN_NCPL is # coupling intervals per NCPL_BASE_PERIOD (default 'day')
+# OCN_NCPL == 4 sets the ocean coupling time to 6 hours.
+# Since OCN_NCPL and GLC_NCPL default to the same value, I am
+# keeping them the same.
 
+./xmlchange GLC_NCPL=1
 ./xmlchange OCN_NCPL=1
 
 # These are archiving options that may be used.
@@ -490,6 +507,46 @@ endif
 
 ./xmlchange DEBUG=FALSE
 ./xmlchange INFO_DBUG=0
+
+# ==============================================================================
+# Update source files.
+#    Ideally, using DART would not require any modifications to the model source.
+#    Until then, this script accesses sourcemods from a hardwired location.
+#    If you have additional sourcemods, they will need to be merged into any DART
+#    mods and put in the SourceMods subdirectory found in the 'caseroot' directory.
+# ==============================================================================
+
+if (    -d     ~/${cesmtag}/SourceMods ) then
+   ${COPY} -r  ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/
+else
+   echo "ERROR - No SourceMods for this case."
+   echo "ERROR - No SourceMods for this case."
+   echo "DART requires modifications to several src files."
+   echo "Download the appropriate files for CESM 1_2_1 from:"
+   echo "http://www.image.ucar.edu/pub/DART/CESM"
+   echo "untar these into your HOME directory - they will create a"
+   echo "~/cesm_1_2_1  directory with the appropriate SourceMods structure."
+   exit -4
+endif
+
+# The CESM multi-instance capability is relatively new and still has a few
+# implementation bugs. These are known problems and will be fixed soon.
+# this should be removed when the files are fixed:
+
+echo "REPLACING BROKEN CESM FILES HERE - SHOULD BE REMOVED WHEN FIXED"
+echo caseroot is ${caseroot}
+if ( -d ~/${cesmtag} ) then
+
+   # preserve the original version of the files
+   if ( ! -e  ${caseroot}/Buildconf/rtm.buildnml.csh.original ) then
+      ${COPY} ${caseroot}/Buildconf/rtm.buildnml.csh \
+              ${caseroot}/Buildconf/rtm.buildnml.csh.original
+   endif
+
+   # patch/replace the broken files (first used by cesm_setup)
+   ${COPY} ~/${cesmtag}/rtm.buildnml.csh  ${caseroot}/Buildconf/.
+
+endif
 
 # ==============================================================================
 # Set up the case.
@@ -534,46 +591,6 @@ switch ( $BATCH )
    default:
    breaksw
 endsw
-
-# ==============================================================================
-# Update source files.
-#    Ideally, using DART would not require any modifications to the model source.
-#    Until then, this script accesses sourcemods from a hardwired location.
-#    If you have additional sourcemods, they will need to be merged into any DART
-#    mods and put in the SourceMods subdirectory found in the 'caseroot' directory.
-# ==============================================================================
-
-if (    -d     ~/${cesmtag}/SourceMods ) then
-   ${COPY} -r  ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/
-else
-   echo "ERROR - No SourceMods for this case."
-   echo "ERROR - No SourceMods for this case."
-   echo "DART requires modifications to several src files."
-   echo "Download the appropriate files for CESM 1_1_1 from:"
-   echo "http://www.image.ucar.edu/pub/DART/CESM"
-   echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_1_1  directory with the appropriate SourceMods structure."
-   exit -4
-endif
-
-# The CESM multi-instance capability is relatively new and still has a few
-# implementation bugs. These are known problems and will be fixed soon.
-# this should be removed when the files are fixed:
-
-echo "REPLACING BROKEN CESM FILES HERE - SHOULD BE REMOVED WHEN FIXED"
-echo caseroot is ${caseroot}
-if ( -d ~/${cesmtag} ) then
-
-   # preserve the original version of the files
-   if ( ! -e  ${caseroot}/preview_namelists.original ) then
-      ${COPY} ${caseroot}/preview_namelists \
-              ${caseroot}/preview_namelists.original
-   endif
-
-   # patch/replace the broken files
-   ${COPY} ~/${cesmtag}/preview_namelists ${caseroot}/.
-
-endif
 
 # ==============================================================================
 # Modify namelist templates for each instance.
@@ -624,15 +641,16 @@ while ($inst <= 1)
    #
    # README:
    # Configuring the contents of the history files for POP is best explained in
-   # the section marked "POP2: TAVG Settings" in the cesm1_1_1 pop2 namelist documentation
-   # http://www.cesm.ucar.edu/models/cesm1.1/cesm/doc/modelnl/nl_pop2.html
+   # the section marked "POP2: TAVG Settings" in the cesm1_2_1 pop2 namelist documentation
+   # http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/modelnl/nl_pop2.html
    #
    # and the CESM-specific documentation for the tavg output variables in the pop2
    # online documentation:
-   # http://www.cesm.ucar.edu/models/cesm1.1/pop2/doc/users/node78.html
+   # http://www.cesm.ucar.edu/models/cesm1.2/pop2/doc/users/node78.html
    #
-   # In CESM1_1_1 keep the values for tavg_file_freq_opt and tavg_freq_opt identical.
-   # pop2/trunk_tags/cesm_pop_2_1_20130412  explains the issue.
+   # In CESM1_2_1 keep the values for tavg_file_freq_opt and tavg_freq_opt identical.
+   # https://svn-ccsm-models.cgd.ucar.edu/pop2/trunk_tags/cesm_pop_2_1_20130416
+   # explains the issue.
    #
    # DEFAULT values for these are:
    # tavg_file_freq_opt = 'nmonth' 'nmonth' 'once'
@@ -640,9 +658,6 @@ while ($inst <= 1)
    # The  first entry indicates we get a monthly average once a month.
    # The second entry indicates we get a monthly average as it is being created.
    # The  third entry indicates  we get a daily timeslice
-   #
-   # Default copies of SourceMods/src.pop2/ocn.*.tavg.csh files are provided in the
-   # DART_SourceMods_cesm1_1_1.tar bundle.
 
    echo "init_ts_suboption  = 'data_assim'" >> ${fname}
 
@@ -778,7 +793,7 @@ if ( \${CONTINUE_RUN} == TRUE ) then
    if (  \${DOUT_S} == TRUE ) then
 
       # The restarts should be in the short term archive directory.  See
-      # www.cesm.ucar.edu/models/cesm1.1/cesm/doc/usersguide/x1631.html#running_ccsm_restart_back
+      # www.cesm.ucar.edu/models/cesm1.2/cesm/doc/usersguide1_2/x1565.html#running_ccsm_restarts
       # for more help and information.
 
       set RESTARTDIR = \${DOUT_S_ROOT}/rest/\${restart_time}
