All changes should not change answers.
* default casenames contain CESM version
* protect against using unsupported compsets
* using environment variable for MPI_RUN_COMMAND instead of hardcoded mpirun.lsf
* correct comment about the name of the HOME/cesm1_* Sourcemods directory
* removed trailing commas from things in the CESM user namelists
* belt and suspenders and new change-in-one-place timestamp for stage_cesm_files



git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/trunk@7370 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 4bf6363e451526bf1da677eaab0070a93b460bfd

diff --git a/models/POP/shell_scripts/CESM1_1_1_setup_hybrid b/models/POP/shell_scripts/CESM1_1_1_setup_hybrid
--- a/models/POP/shell_scripts/CESM1_1_1_setup_hybrid
+++ b/models/POP/shell_scripts/CESM1_1_1_setup_hybrid
@@ -98,7 +98,7 @@
 # num_instances The number of ensemble members.
 # ==============================================================================
 
-setenv case                 pop_1_1_1_hybrid
+setenv case                 pop1_1_1_hybrid
 setenv compset              GIAF
 setenv resolution           T62_gx1v6
 setenv cesmtag              cesm1_1_1
@@ -341,6 +341,16 @@ cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
 
+# Make sure the land and atmosphere are 'data' components.
+
+if ( (${COMP_ATM} != datm) || (${COMP_LND} != slnd) ) then
+   echo " "
+   echo "ERROR: This setup script is not appropriate for active land or atmosphere compsets."
+   echo "ERROR: Please use the models/CESM/shell_scripts examples for these cases."
+   echo " "
+   exit -3
+endif
+
 # MAX_TASKS_PER_NODE comes from $case/Tools/mkbatch.$machine
 @ ptile = $MAX_TASKS_PER_NODE / 2
 @ nthreads = 1
@@ -552,7 +562,7 @@ else
    echo "Download the appropriate files for CESM 1_1_1 from:"
    echo "http://www.image.ucar.edu/pub/DART/CESM"
    echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_1_1  directory with the appropriate SourceMods structure."
+   echo "~/cesm1_1_1  directory with the appropriate SourceMods structure."
    exit -4
 endif
 
diff --git a/models/POP/shell_scripts/CESM1_2_1_setup_hybrid b/models/POP/shell_scripts/CESM1_2_1_setup_hybrid
--- a/models/POP/shell_scripts/CESM1_2_1_setup_hybrid
+++ b/models/POP/shell_scripts/CESM1_2_1_setup_hybrid
@@ -98,7 +98,7 @@
 # num_instances The number of ensemble members.
 # ==============================================================================
 
-setenv case                 pop_1_2_1_hybrid
+setenv case                 pop1_2_1_hybrid
 setenv compset              GIAF
 setenv resolution           T62_gx1v6
 setenv cesmtag              cesm1_2_1
@@ -341,11 +341,11 @@ cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
 
-# Check to make sure the land and atmosphere are 'data' components.
+# Make sure the land and atmosphere are 'data' components.
 
-if ( $?CLM_CONFIG_OPTS || $?CAM_DYCORE ) then
+if ( (${COMP_ATM} != datm) || (${COMP_LND} != slnd) ) then
    echo " "
-   echo "ERROR: This setup script is not appropriate for active land or atmosphere models."
+   echo "ERROR: This setup script is not appropriate for active land or atmosphere compsets."
    echo "ERROR: Please use the models/CESM/shell_scripts examples for these cases."
    echo " "
    exit -3
@@ -526,7 +526,7 @@ else
    echo "Download the appropriate files for CESM 1_2_1 from:"
    echo "http://www.image.ucar.edu/pub/DART/CESM"
    echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_2_1  directory with the appropriate SourceMods structure."
+   echo "~/cesm1_2_1  directory with the appropriate SourceMods structure."
    exit -4
 endif
 
@@ -607,6 +607,7 @@ while ($inst <= $num_instances)
    set fname = "user_nl_datm${inst_string}"
    # ===========================================================================
    # DATM Namelist
+
    echo "dtlimit  = 1.5, 1.5"               >> ${fname}
    echo "fillalgo = 'nn', 'nn'"             >> ${fname}
    echo "fillmask = 'nomask','nomask'"      >> ${fname}
diff --git a/models/clm/shell_scripts/CESM1_1_1_setup_pmo b/models/clm/shell_scripts/CESM1_1_1_setup_pmo
--- a/models/clm/shell_scripts/CESM1_1_1_setup_pmo
+++ b/models/clm/shell_scripts/CESM1_1_1_setup_pmo
@@ -6,7 +6,7 @@
 #
 # DART $Id$
 
-# ==============================================================================
+#*******************************************************************************
 #
 # ---------------------
 # Purpose
@@ -92,9 +92,7 @@
 # ./${case}.clean_build
 # ./${case}.build
 #
-# ==============================================================================
-
-
+#*******************************************************************************
 
 # ==============================================================================
 # case options:
@@ -108,7 +106,7 @@
 # cesmtag       The version of the CESM source code to use when building the code.
 # ==============================================================================
 
-setenv case                 clm4_1_1_1_pmo
+setenv case                 clm1_1_1_pmo
 setenv compset              I_2000_CN
 setenv resolution           f09_f09
 setenv cesmtag              cesm1_1_1
@@ -384,6 +382,16 @@ cd ${caseroot}
 
 source ./Tools/ccsm_getenv || exit -2
 
+# Make sure the case is configured with a data ocean and a data atmosphere.
+
+if ( (${COMP_OCN} != docn) || (${COMP_ATM} != datm) ) then
+   echo " "
+   echo "ERROR: This setup script is not appropriate for active ocean or atmospheric compsets."
+   echo "ERROR: Please use the models/CESM/shell_scripts examples for that case."
+   echo " "
+   exit -3
+endif
+
 # MAX_TASKS_PER_NODE comes from $case/Tools/mkbatch.$machine
 @ ptile = $MAX_TASKS_PER_NODE / 2
 @ nthreads = 1
@@ -522,6 +530,8 @@ endif
 # This creates the EXEROOT and RUNDIR directories.
 # ==============================================================================
 
+echo 'Setting up the case ...'
+
 ./cesm_setup
 
 if ( $status != 0 ) then
@@ -556,7 +566,6 @@ switch ( $BATCH )
    breaksw
 
    default:
-
    breaksw
 endsw
 
@@ -581,7 +590,7 @@ else
    echo "Download the appropriate files for CESM 1_1_1 from:"
    echo "http://www.image.ucar.edu/pub/DART/CESM"
    echo "untar these into your HOME directory - they will create a"
-   echo "~/cesm_1_1_1  directory with the appropriate SourceMods structure."
+   echo "~/cesm1_1_1  directory with the appropriate SourceMods structure."
    exit -4
 endif
 
@@ -649,7 +658,7 @@ while ($inst <= 1)
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
    # ===========================================================================
-   # LAND namelist
+   # LAND Namelist
    # With a RUN_TYPE=hybrid the finidat is automatically specified
    # using the REFCASE/REFDATE/REFTOD information. i.e.
    # finidat = ${stagedir}/${refcase}.clm2${inst_string}.r.${reftimestamp}.nc
@@ -715,10 +724,10 @@ while ($inst <= 1)
    # For a HOP TEST ... hist_empty_htapes = .false.
    # For a HOP TEST ... use a default hist_fincl1
 
-   echo "dtime             = $clm_dtime,"             >> ${fname}
-   echo "hist_empty_htapes = .false.,"                >> ${fname}
-   echo "hist_fincl1 = 'NEP',"                        >> ${fname}
-   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R',"  >> ${fname}
+   echo "dtime             = $clm_dtime"              >> ${fname}
+   echo "hist_empty_htapes = .false."                 >> ${fname}
+   echo "hist_fincl1 = 'NEP'"                         >> ${fname}
+   echo "hist_fincl2 = 'NEP','FSH','EFLX_LH_TOT_R'"   >> ${fname}
    echo "hist_fincl3 = 'TV','TLAI','PBOT','TBOT','TSA','RH2M_R','SNOWDP'" >> ${fname}
    echo "hist_nhtfrq = -$stop_n,1,-$stop_n"           >> ${fname}
    echo "hist_mfilt  = 1,$h1nsteps,1"                 >> ${fname}
@@ -821,7 +830,6 @@ cat << EndOfText >! stage_cesm_files
 
 set restart_time = $init_time
 
-
 # get the settings for this case from the CESM environment
 cd ${caseroot}
 source ./Tools/ccsm_getenv || exit -2
@@ -837,7 +845,6 @@ else
   echo "Date to reset files to is: ${init_time}"
 endif
 echo ''
-
 
 if ( \${CONTINUE_RUN} == TRUE ) then
 
