Merged improvements from Zagar's OSSE development.
--------------
All:
   Better comments.
   Improvements from more testing.
*  This version is untested.

--------------
models/cam-fv/shell_scripts/cesm2_1/

compress.csh
   Handle previously (de)compressed files.

DART_config.template
   Replaced num_instances with CESM's NINST
   Fixed DART_SCRIPTS_DIR directory redundancy.
   Define CIMEROOT env variable with value from setup_ to enable
     xmlchange.
   Substitute job characteristics into directives in *compress.csh
     and launch_cf.sh.
   Updated 'next steps' instructions.

assimilate.csh.template
   Make save_rest_freq handle day of the week (and every Nth day).
   Better purging of rh and h0 and stages_except_output files.
   Reduce unneeded listings of files, to save time.
   More selective hiding of files from the purging process.
   Only compress cpl history files if they exist.

setup_*
   Made more consistent with each other, including CAM external forcing,
     which matches what was used in the Reanalysis.
   Sed more case descriptors into DART_config
   Added warning about absence of inflation restart file to
     stage_cesm_files (since they are restarts).
     ? Maybe that should be done in DART_config.
setup_advanced
   Updated high res. SST file to the 2011-2020 version.
   Added some error numbers to exits.
   Added fix of docn.stream time labels after preview_namelists
     creates them.
setup_hybrid
   Updated for (1 degree) CESM2_1.
   Added (missing) optional call to DART_config.
setup_pmo
   Consolidated MultiInstanceRefcase into TRUTHinstance.
   Removed high resolution SST option (excessive for OSSEs).

--------------
models/cam-fv/work/input.nml
   Replaced stage preassim with forecast, to provide uninflated members
     (the means are identical).
   Replaced inflation flavor with enhanced adaptive (5).
   Imported improvement to hlevel_edges to reflect no GPS obs below 200m
     which improves plot appearance.
   Changed several variables to values most often used in CAM assims.

diff --git a/models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template b/models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template
--- a/models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template
+++ b/models/cam-fv/shell_scripts/cesm2_1/assimilate.csh.template
@@ -3,8 +3,6 @@
 # DART software - Copyright UCAR. This open source software is provided
 # by UCAR, "as is", without charge, subject to all terms of use at
 # http://www.image.ucar.edu/DAReS/DART/DART_download
-#
-# DART $Id$
 
 # ------------------------------------------------------------------------------
 # Purpose: assimilate with a CAM ensemble and perform advanced archiving
@@ -342,7 +340,7 @@ if ($#log_list >= 3) then
 
    # Find the date of the oldest restart set from filenames like:
    # setup_test.cpl_0001.r.2016-12-11-21600.nc   ... or ...
-   # setup_test.cpl.r.2016-12-11-21600.nc
+   # setup_test.cpl.r.2016-12-11-21600.nc.gz
    #
    # Grab the root of the filename (removes the .nc 'extension')
    # and then the extension is the bit we need.
@@ -357,6 +355,24 @@ if ($#log_list >= 3) then
    set sec_o_day   = $RM_DATE_PARTS[4]
    set day_time    = ${day_o_month}-${sec_o_day}
 
+   # Decide whether to purge restart files at this date and time.
+   set save_rest_freq = BOGUS_save_every_Mth
+   
+   set purge = 'true'
+   # Learn whether save_rest_freq a string or a number.
+   # Character strings must be tested outside of the 'if' statement.
+   echo $save_rest_freq | grep '[a-z]'
+   if ($status == 0) then
+      set purge_date = $RM_DATE_PARTS[1]-$RM_DATE_PARTS[2]-$RM_DATE_PARTS[3]
+      set weekday = `date --date="$purge_date" +%A`
+      if ($weekday == $save_rest_freq) set purge = 'false'
+
+   # Numbers can be tested inside the 'if' statement.
+   else if (`echo $save_rest_freq | grep '[0-9]'`) then
+      if (${day_o_month} % ${save_rest_freq} == 0) set purge = 'false'
+
+   endif
+
    # Identify log files to be removed or moved.
    # [3] means the 3rd oldest restart set is being (re)moved.
    set rm_log = `echo $log_list[3] | sed -e "s/\./ /g;"`
@@ -368,7 +384,7 @@ if ($#log_list >= 3) then
    # The 'else' block preserves the restarts in the archive directory.
 
    if ( $sec_o_day !~ '00000' || \
-       ($sec_o_day =~ '00000' && $day_o_month % BOGUS_save_every_Mth != 0) ) then
+       ($sec_o_day =~ '00000' && $purge == 'true') ) then
 
       # Optionally save inflation restarts, even if it's not a 'save restart' time.
       if ($save_all_inf =~ TRUE) ${MOVE} ${CASE}*inf*${day_time}*  ${archive}/esp/hist
@@ -378,8 +394,14 @@ if ($#log_list >= 3) then
       # Note that *cpl.h[ar]* are retained, and any h#, #>0.
 
       echo "Removing unneeded restart file set (DD_SSSSS ${day_time}) from RUNDIR: "
-      echo "     ${CASE}"'*.{r,rs,rs1,rh0,h0}.*'"${day_time}"
-      ${REMOVE}  ${CASE}*.{r,rs,rs1,rh0,h0}.*${day_time}* &
+      # It's OK to remove rh# (all components) because only the last date is needed,
+      # while this is the 3rd to last date.  Also, if the history output is averaged, 
+      # the averaging period is (should be) the length of the forecast, 
+      # so there will be no running averages stored in the rh# files.
+      # But the h0 files need to be kept if any user specified fields are in them.
+      # They will be handled by repack_st_archive.csh and/or purge.csh later.
+      echo "     ${CASE}"'*.{r,rs,rs1,rh[0-9]}.*'"${day_time}"
+      ${REMOVE}  ${CASE}*.{r,rs,rs1,rh[0-9]}.*${day_time}* &
 
       # Handle .i. separately to avoid sweeping up .i.${scomp}_{in,out}put_{mean,sd,...} files.
       echo "     ${CASE}"'*.i.[0-9]*'"${day_time}"
@@ -387,8 +409,8 @@ if ($#log_list >= 3) then
 
       if ($save_stages_freq =~ NONE || $save_stages_freq =~ RESTART_TIMES) then
          # 'output' will have been renamed by the time the purging happens.
-         echo "     ${CASE}"'*'[0-9].${stages_except_output}'*'${day_time}
-         ${REMOVE}  ${CASE}.*[0-9].${stages_except_output}*${day_time}* &
+         echo "     ${CASE}"'*'[0-9].e.${stages_except_output}'*'${day_time}
+         ${REMOVE}  ${CASE}.*[0-9].e.${stages_except_output}*${day_time}* &
       endif
    else
 
@@ -426,9 +448,9 @@ if ($#log_list >= 3) then
       set save_root = ${archive}/rest/${rm_date}
       if (! -d $save_root) then
          mkdir -p $save_root
-         (${MOVE} ${CASE}*.{r,rs,rs1,rh0,h0}.*${day_time}*  $save_root || exit 60) &
+         (${MOVE} ${CASE}*.{r,rs,rs1,rh[0-9]}.*${day_time}*  $save_root || exit 60) &
          (${MOVE} ${CASE}*.i.[0-9]*${day_time}*             $save_root || exit 61) &
-         (${COPY} *.output*inf*${day_time}*                 $save_root || exit 62) &
+         (${COPY} *output*inf*${day_time}*                  $save_root || exit 62) &
          (${MOVE} *0001*${rm_log[$rm_slot]}*                $save_root || exit 63) &
          (${MOVE} cesm*${rm_log[$rm_slot]}*                 $save_root || exit 64) &
       else
@@ -437,7 +459,8 @@ if ($#log_list >= 3) then
       endif
    endif
 
-   # Remove log files: *YYMMDD-HHMMSS*.  Except not da.log files
+   # Remove log files: *YYMMDD-HHMMSS*, except not da.log files, after moves and copies are done.
+   wait
    ${REMOVE}  [^d]*${rm_log[$rm_slot]}*  &
 
    # I'd like to remove the CAM .r. files, since we always use the .i. files to do a hybrid start,
@@ -513,13 +536,16 @@ ${REMOVE} ${CAMINPUT}
 ${LINK} ${CASE}.cam_0001.i.${ATM_DATE_EXT}.nc ${CAMINPUT} || exit 90
 
 # All of the .h0. files contain the same PHIS field, so we can link to any of them.
-
-set HISTS = `${LIST} ${CASE}.cam_0001.h0.*.nc`
 set MYSTRING = `grep cam_phis_filename input.nml`
 set MYSTRING = `echo $MYSTRING | sed -e "s#[=,']# #g"`
 set CAM_PHIS = $MYSTRING[2]
-${REMOVE} ${CAM_PHIS}
-${LINK} $HISTS[1] ${CAM_PHIS} || exit 100
+# Avoid doing LISTs in rundir; only search for an h0 file if cam_phis.nc doesn't exist.
+if (! -f ${CAM_PHIS}) then
+   # -r puts the file with the latest date first in the list.
+   # It won't be purged during this cycle by the cleanup (above).
+   set hists = (`${LIST} -r ${CASE}.cam_0001.h0.*.nc`)
+   ${COPY} $hists[1] ${CAM_PHIS} || exit 100
+endif
 
 # Now, actually check the inflation settings
 
@@ -589,6 +615,8 @@ if ($USING_PRIOR_INFLATION == true) then
    else
       # Look for the output from the previous assimilation (or fill_inflation_restart)
       # If inflation files exists, use them as input for this assimilation
+      # TODO: This should probably look for a date, instead of relying on the files
+      #       we want being the youngest in the directory.
       (${LIST} -rt1 *.dart.rh.${scomp}_output_priorinf_mean* | tail -n 1 >! latestfile) > & /dev/null
       (${LIST} -rt1 *.dart.rh.${scomp}_output_priorinf_sd*   | tail -n 1 >> latestfile) > & /dev/null
       set nfiles = `cat latestfile | wc -l`
@@ -622,7 +650,7 @@ if ($USING_PRIOR_INFLATION == true) then
 
       else
          echo "ERROR: Requested PRIOR inflation restart, "
-         echo '       but files *.dart.rh.${scomp}_output_priorinf_* do not exist in the ${RUNDIR}.'
+         echo "       but files *.dart.rh.${scomp}_output_priorinf_* do not exist in the ${RUNDIR}."
          echo '       If you are changing from cam_no_assimilate.csh to assimilate.csh,'
          echo '       you might be able to continue by changing CONTINUE_RUN = FALSE for this cycle,'
          echo '       and restaging the initial ensemble.'
@@ -783,7 +811,7 @@ echo "`date` -- BEGIN FILE RENAMING"
 # '_####.i.' files are CESM initial files.
 # '.dart.i.' files are ensemble statistics (mean, sd) of just the state variables 
 #            in the initial files.
-# '.e.'      designates a file as something from the 'external system processing ESP', e.g. DART.
+# '.e.'      files are from the 'external system processing (ESP)', e.g. DART.
 
 foreach FILE (`${LIST} ${stages_all}_member_*.nc`)
 
@@ -810,7 +838,8 @@ end
 # But they still need to be different for each component, so include $scomp in the
 # ".dart_file" part of the file name.  Somewhat awkward and inconsistent, but effective.
 
-# Means and standard deviation files (except for inflation).
+# Means and standard deviation files (except for inflation; 
+# excluded by, e.g., mean right after stage).
 foreach FILE (`${LIST} ${stages_all}_{mean,sd}*.nc`)
 
    set parts = `echo $FILE | sed -e "s#\.# #g"`
@@ -876,7 +905,7 @@ end
 # CAM starts from the initial file name specified in atm_in:ncdata,
 # but writes an initial file at the end which has a CESM convention name.
 # That file needs to be linked to the namelist file name.
-# The first cycle link is made by state_cesm_files.
+# The first cycle link is made by stage_cesm_files.
 # The subsequent links are made here.
 set member = 1
 while ( ${member} <= ${ensemble_size} )
@@ -918,11 +947,11 @@ if ($cycle == $DATA_ASSIMILATION_CYCLES) then
       if ($save_all_inf =~ TRUE) then
          # Put the previous and current inflation restarts in the archive directory.
          # (to protect last from st_archive putting them in exp/hist)
-         ${MOVE}   ${CASE}*${stages_except_output}*inf*  ${archive}/esp/rest
+         ${MOVE}   ${CASE}*${stages_except_output}*inf*  ${archive}/esp/hist
 
          # Don't need previous inf restarts now, but want them to be archived later.
          # COPY instead of LINK because they'll be moved or used later.
-         ${COPY}   ${CASE}*output*inf* ${archive}/esp/rest
+         ${COPY}   ${CASE}*output*inf* ${archive}/esp/hist
       else
          # output*inf must be copied back because it needs to be in ${RUNDIR}
          # when st_archive runs to save the results of the following assim
@@ -933,7 +962,13 @@ if ($cycle == $DATA_ASSIMILATION_CYCLES) then
       endif
 
       # Hide the CAM 'restart' files from the previous cycle (day_time) from the archiver.
-      ${MOVE}           ${CASE}*.{r,rs,rs1,rh0,h0,i}.*${day_time}*    $hidedir
+      # Be more selective about file dates to move.
+      # This old one moved previous months of .i. {mean,sd} files,
+      # which prevented them from being archived to esp/hist
+      ${MOVE}           ${CASE}*.{r,rs,rs1}.*${hide_date}*    $hidedir
+      # Don't move the ...dart.i.cam_*{mean,sd} files,
+      # but move the ...{instance}.i. files.
+      ${MOVE}           ${CASE}*[^t].i.*${hide_date}*    $hidedir
 
       # Move log files: *YYMMDD-HHMMSS.  [2] means the previous restart set is being moved.
       set rm_log = `echo $log_list[2] | sed -e "s/\./ /g;"`
@@ -941,6 +976,14 @@ if ($cycle == $DATA_ASSIMILATION_CYCLES) then
       set rm_slot = $#rm_log
       if ($rm_log[$#rm_log] =~ gz) @ rm_slot--
       ${MOVE}  *$rm_log[$rm_slot]*  $hidedir
+      # Also COPY the most recent log files ([1]) so that they will be returned to rundir
+      # for the next job, and there will be the right number to trigger the archiving
+      # of inflation files to esp/hist for prevmo-lastdayprevjob-64800
+      set rm_log = `echo $log_list[1] | sed -e "s/\./ /g;"`
+      # -- (decrement by one) skips the gz at the end of the names.
+      set rm_slot = $#rm_log
+      if ($rm_log[$#rm_log] =~ gz) @ rm_slot--
+      ${COPY}  *$rm_log[$rm_slot]*  $hidedir
    endif
 
    # Restore CESM's timing logic for the first cycle of the next job.
@@ -983,36 +1026,36 @@ ___EndOfText
 
    echo "`date` -- END   ARCHIVING LOGIC"
 
-   # DEBUG st_archive by making a shadow copy of this directory.
-   module load nco
-
-   if (-d ../run_shadow) ${REMOVE} -f ../run_shadow
-   mkdir ../run_shadow
-
-   set comps = ('cam_'  'clm2_'  'mosart_' 'dart')
-   set vars  = ('nhfil' 'locfnh' 'locfnh'  'restart_hist')
-
-   foreach f (`$LIST[1]`)
-      set gr_stat = 1
-      echo $f | grep '\.r\.'
-      if ($status == 0) then
-         set c = 1
-         while ($c <= $#comps) 
-            echo $f | grep $comps[$c]
-            if ($status == 0) then
-               echo "c = $c for $f"
-#                set echo verbose
-               set gr_stat = 0
-               ncks -O -v $vars[$c] $f ../run_shadow/$f
-               break
-            endif
-            @ c++
-         end
-      endif
-      if ($gr_stat == 1) then
-         ${LIST} -l $f >! ../run_shadow/$f
-      endif
-   end
+#    # DEBUG st_archive by making a shadow copy of this directory.
+#    module load nco
+# 
+#    if (-d ../run_shadow) ${REMOVE} -f ../run_shadow
+#    mkdir ../run_shadow
+# 
+#    set comps = ('cam_'  'clm2_'  'mosart_' 'dart')
+#    set vars  = ('nhfil' 'locfnh' 'locfnh'  'restart_hist')
+# 
+#    foreach f (`$LIST[1]`)
+#       set gr_stat = 1
+#       echo $f | grep '\.r\.'
+#       if ($status == 0) then
+#          set c = 1
+#          while ($c <= $#comps) 
+#             echo $f | grep $comps[$c]
+#             if ($status == 0) then
+#                echo "c = $c for $f"
+# #                set echo verbose
+#                set gr_stat = 0
+#                ncks -O -v $vars[$c] $f ../run_shadow/$f
+#                break
+#             endif
+#             @ c++
+#          end
+#       endif
+#       if ($gr_stat == 1) then
+#          ${LIST} -l $f >! ../run_shadow/$f
+#       endif
+#    end
 
 endif
 
@@ -1020,19 +1063,22 @@ endif
 # Compress the large coupler history files and DART files.
 # ==============================================================================
 
-echo "STARTING: compressing coupler history files and DART files at `date`"
-
-${CASEROOT}/compress.csh $CASE $ATM_DATE_EXT $ensemble_size "hist dart" "$stages_all"
-if ($status != 0) then
-   echo "ERROR: Compression of coupler history files and DART files failed at `date`"
-   # Ensure the removal of unneeded restart sets and copy of obs_seq.final are finished.
-   wait
-   exit 250
+grep ha2x drv_in >& /dev/null
+if ($status == 0) then
+   echo "STARTING: compressing coupler history files at `date`"
+   ${CASEROOT}/compress.csh $CASE $ATM_DATE_EXT ensemble size "hist" "$stages_all"
+   
+   if ($status != 0) then
+      echo "ERROR: Compression of coupler history files failed at `date`"
+      # Ensure the removal of unneeded restart sets and copy of obs_seq.final are finished.
+      wait
+      exit 250
+   endif
+   
+   echo "FINISHED: compressing coupler history files and DART files at `date`"
+   echo "`date` -- END CAM_ASSIMILATE"
 endif
-
-echo "FINISHED: compressing coupler history files and DART files at `date`"
-echo "`date` -- END CAM_ASSIMILATE"
-
+   
 # Ensure the removal of unneeded restart sets and copy of obs_seq.final are finished.
 wait
 
