Add fixes from testing setup_*
setup_pmo
setup_hybrid
setup_advanced
   Updated resolution examples, and web site to find more.
   Replaced generic cesm2_1 cesmtag with one that has a SourceMods.
   Replaced 1 degree, monthly, SST file with one that extends through
      2020 (actually part of 2021).
   Check whether start_year is withing the SST data file years.
   Print the git branch.
   More consistency between these 3 scripts.

submit_compress.csh
   Compress.csh is usually called from assimilate.csh,
   but sometimes it's run as a separate job.

launch_cf.sh
   Script to run shell script commands in parallel using
   the "command file" mechanism.
   Used by compress.csh

diff --git a/models/cam-fv/shell_scripts/cesm2_1/setup_advanced b/models/cam-fv/shell_scripts/cesm2_1/setup_advanced
--- a/models/cam-fv/shell_scripts/cesm2_1/setup_advanced
+++ b/models/cam-fv/shell_scripts/cesm2_1/setup_advanced
@@ -137,9 +137,9 @@
 #               https://ncar.github.io/CAM/doc/build/html/users_guide/atmospheric-configurations.html
 #               and carefully incorporate any needed changes into this script.
 # resolution    Defines the horizontal resolution and dynamical core;
-#               see http://esmci.github.io/cime/users_guide/grids.html.
-#               f19_f19  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
-#               f09_f09  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
+#               see https://www.cesm.ucar.edu/models/cesm2/config/2.1.0/grids.html
+#               f19_f19_mg17  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
+#               f09_f09_mg17  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
 #               To use the high resolution SST data ocean, use resolution "f09_d025" or "f19_d025"
 #               and the user_grid variable.
 #               > set user_grid = "${user_grid} --gridfile /glade/work/raeder/Models/CAM_init/SST"
@@ -157,13 +157,13 @@ setenv compset         HIST_CAM60_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_
 setenv user_grid       ''
 #      alias: f09_f09_mg17 (only for compsets that are not _POP and no CISM)
 setenv resolution      f09_d025
-setenv cesmtag         cesm2_1
+setenv cesmtag         cesm2_1_relsd_m5.6
 setenv num_instances   3
 
 # If cemstag >= cesm2_0_alpha10f and compset = FHIST_DARTC6 (or another non-supported):
 # and resolution is non-standard (e.g. d025)
-setenv compset_args     "--compset $compset"
-setenv compset_args "${compset_args} --run-unsupported"
+setenv compset_args   "--compset $compset"
+setenv compset_args   "${compset_args} --run-unsupported"
 
 # ==============================================================================
 # machines and directories:
@@ -229,7 +229,7 @@ setenv baseobsdir   /glade/p/cisl/dares/Observations/NCEP+ACARS+GPS
 # refyear    The specific date/time-of-day in the reference case that this
 # refmon     run will start from.  (Also see 'runtime settings' below for
 # refday     start_year, start_mon, start_day and start_tod.)
-# reftod
+# reftod     NOTE; there must be obs_seq.out files for these dates.
 # NOTE:      All the ref* variables must be treated like strings and have
 #            the appropriate number of preceeding zeros. 
 #
@@ -300,13 +300,13 @@ set nthreads = 1
 # Examples are provided here.
 # "2 degree":
 # setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2016_c170525.nc
-# setenv sst_grid ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
+# setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
 # "1 degree":
-# setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2016_c170525.nc
-# setenv sst_grid ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
+# setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2020_c210521.nc
+# setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
 # Specify the beginning and ending years of the data set.
 # setenv sst_year_start 1850
-# setenv sst_year_end   2016
+# setenv sst_year_end   2021
 
 # "1/4 degree":
 # A better alternative is daily, 1/4-degree SSTs from Reynolds,...,Tomas
@@ -327,6 +327,10 @@ endif
 setenv sst_grid    /glade/work/raeder/Models/CAM_init/SST/domain.ocn.d025.120821.nc
 setenv sst_year_start $start_year
 setenv sst_year_end   $start_year
+if ($start_year > $sst_year_end) then
+   echo "ERROR: start_year is later then sst_year_end"
+   exit 6
+endif
 
 # ==============================================================================
 # job settings:
@@ -358,11 +362,11 @@ setenv email        YOUR@email.address
 set nonomatch       # suppress "rm" warnings if wildcard does not match anything
 
 set VERBOSE = '-v'
-set   MOVE  = '/usr/bin/mv'
-set   COPY  = '/usr/bin/cp --preserve=timestamps'
-set   LINK  = '/usr/bin/ln -s'
-set   LIST  = '/usr/bin/ls'
-set REMOVE  = '/usr/bin/rm'
+set    MOVE = '/usr/bin/mv'
+set    COPY = '/usr/bin/cp --preserve=timestamps'
+set    LINK = '/usr/bin/ln -s'
+set    LIST = '/usr/bin/ls'
+set  REMOVE = '/usr/bin/rm'
 
 # ==============================================================================
 # ==============================================================================
@@ -379,6 +383,8 @@ if ($?LS_SUBCWD) then
 else if ($?PBS_O_WORKDIR) then
    cd $PBS_O_WORKDIR
 endif
+echo "Using the starred branch of `pwd`"
+git branch
 
 # Store the location of these setup scripts for use in DART_config.
 set DART_CESM_scripts = `pwd`
@@ -976,7 +982,7 @@ while ($inst <= $num_instances)
       endif
    endif
 
-   # if ($start_year > 2008) then
+#    if ($start_year > 2008) then
       # The default as of April 2015 is
       # /glade/p/cesmdata/cseg/inputdata/atm/cam/solar/SOLAR_SPECTRAL_Lean_1610-2008_annual_c090324.nc
       # For later dates there are files which repeat the solar cycles from 1960-2008
@@ -985,8 +991,8 @@ while ($inst <= $num_instances)
       # This does not look like an exact extension of the default,
       # but does look like the previous default.  So try it.
 
-   #    echo " solar_data_file = '${cesmdata}/atm/cam/solar/spectral_irradiance_Lean_1610-2140_ann_c100408.nc'" >> ${fname}
-   # endif
+#       echo " solar_data_file = '${cesmdata}/atm/cam/solar/spectral_irradiance_Lean_1610-2140_ann_c100408.nc'" >> ${fname}
+#    endif
 
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
@@ -1370,7 +1376,8 @@ Time to run the first job
 6)  Submit the job (and get mail when it starts and stops):
     ./case.submit -M begin,end --skip-preview-namelist
 
-7)  After the job has run, check to make sure it worked.
+7)  After the job has run, check to make sure it worked;
+    expected files are there, observation space diagnostics, ...
 
 Additional cycles.
 
diff --git a/models/cam-fv/shell_scripts/cesm2_1/setup_hybrid b/models/cam-fv/shell_scripts/cesm2_1/setup_hybrid
--- a/models/cam-fv/shell_scripts/cesm2_1/setup_hybrid
+++ b/models/cam-fv/shell_scripts/cesm2_1/setup_hybrid
@@ -135,9 +135,9 @@
 #               https://ncar.github.io/CAM/doc/build/html/users_guide/atmospheric-configurations.html
 #               and carefully incorporate any needed changes into this script.
 # resolution    Defines the horizontal resolution and dynamical core;
-#               see http://esmci.github.io/cime/users_guide/grids.html.
-#               f19_f19  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
-#               f09_f09  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
+#               see https://www.cesm.ucar.edu/models/cesm2/config/2.1.0/grids.html
+#               f19_f19_mg17  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
+#               f09_f09_mg17  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
 # cesmtag       The version of the CESM source code to use when building the model.
 #               The assimilate.csh in this directory will handle only cesm2_0 and later.
 # num_instances The number of ensemble members.
@@ -149,13 +149,13 @@
 setenv case            Test0
 setenv compset         HIST_CAM60_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
 # setenv compset         FHIST_DARTC6
-setenv resolution      f09_f09
-setenv cesmtag         cesm2_1
+setenv resolution      f09_f09_mg17
+setenv cesmtag         cesm2_1_relsd_m5.6
 setenv num_instances   3
 
 # If cemstag >= cesm2_0_alpha10f and compset = FHIST_DARTC6 (or another non-supported):
-setenv compset_args     "--compset $compset"
-setenv compset_args "${compset_args} --run-unsupported"
+setenv compset_args   "--compset $compset"
+setenv compset_args   "${compset_args} --run-unsupported"
 
 # ==============================================================================
 # machines and directories:
@@ -208,7 +208,8 @@ setenv dartroot     /glade/u/home/${USER}/DART/your_DART
 setenv cime_output  /glade/scratch/${USER}
 setenv archdir      ${cime_output}/${case}/archive
 
-setenv baseobsdir   /glade/p/cisl/dares/Observations/NCEP+ACARS+GPS
+# setenv baseobsdir   /glade/p/cisl/dares/Observations/NCEP+ACARS+GPS
+setenv baseobsdir   /glade/p/cisl/dares/Observations/Synthetic/UVTRadiosonde_3456
 
 # ==============================================================================
 # Initial conditions files:
@@ -221,7 +222,7 @@ setenv baseobsdir   /glade/p/cisl/dares/Observations/NCEP+ACARS+GPS
 # refyear    The specific date/time-of-day in the reference case that this
 # refmon     run will start from.  (Also see 'runtime settings' below for
 # refday     start_year, start_mon, start_day and start_tod.)
-# reftod
+# reftod     NOTE; there must be obs_seq.in files for these dates.
 # NOTE:      All the ref* variables must be treated like strings and have
 #            the appropriate number of preceeding zeros. 
 #
@@ -244,7 +245,7 @@ setenv reftimestamp $refyear-$refmon-$refday-$reftod
 setenv stagedir /glade/work/${USER}/Models/CAM_init/FV1deg_cesm2_1/${reftimestamp}
 
 # ==============================================================================
-# runtime settings: 
+# runtime settings:
 #    This script will find usable CAM external forcing files for years 19mumble-2015.
 #    Years after that (or before) may require searching $cesmdata for more
 #    up-to-date files and adding them to the user_nl_cam_#### in the code below.
@@ -293,14 +294,18 @@ set nthreads = 1
 # Examples are provided here.
 # "2 degree":
 # setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2016_c170525.nc
-# setenv sst_grid ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
+# setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
 # "1 degree":
-setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2016_c170525.nc
-sst_grid ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
+setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2020_c210521.nc
+setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
 # Specify the beginning and ending years of the data set.
 setenv sst_year_start 1850
-setenv sst_year_end   2016
+setenv sst_year_end   2021
 
+if ($start_year > $sst_year_end) then
+   echo "ERROR: start_year is later then sst_year_end"
+   exit 6
+endif
 
 # ==============================================================================
 # job settings:
@@ -353,6 +358,8 @@ if ($?LS_SUBCWD) then
 else if ($?PBS_O_WORKDIR) then
    cd $PBS_O_WORKDIR
 endif
+echo "Using the starred branch of `pwd`"
+git branch
 
 # Store the location of these setup scripts for use in DART_config.
 set DART_CESM_scripts = `pwd`
@@ -441,7 +448,7 @@ ${CIMEROOT}/scripts/create_newcase \
    --ninst    $num_drivers    \
    $compset_args              \
    $multi_driver
-    
+
 if ( $status != 0 ) then
    echo "ERROR: Case could not be created."
    exit 15
@@ -994,6 +1001,7 @@ while ($inst <= $num_instances)
    @ inst ++
 
 end
+echo ' '
 
 # ===========================================================================
 # set fname = "user_nl_cpl"
diff --git a/models/cam-fv/shell_scripts/cesm2_1/setup_pmo b/models/cam-fv/shell_scripts/cesm2_1/setup_pmo
--- a/models/cam-fv/shell_scripts/cesm2_1/setup_pmo
+++ b/models/cam-fv/shell_scripts/cesm2_1/setup_pmo
@@ -140,9 +140,9 @@
 #               https://ncar.github.io/CAM/doc/build/html/users_guide/atmospheric-configurations.html
 #               and carefully incorporate any needed changes into this script.
 # resolution    Defines the horizontal resolution and dynamical core;
-#               see http://esmci.github.io/cime/users_guide/grids.html.
-#               f19_f19  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
-#               f09_f09  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
+#               see https://www.cesm.ucar.edu/models/cesm2/config/2.1.0/grids.html
+#               f19_f19_mg17  ... FV core at ~ 2 degree (19 means 1.9 degrees of latitude).
+#               f09_f09_mg17  ... FV core at ~ 1 degree (the 2nd f09 means CLM uses a .9 degree latitude grid)
 # cesmtag       The version of the CESM source code to use when building the model.
 #
 # Guidelines on what to change for a WACCM run are described in the 
@@ -152,8 +152,8 @@
 setenv case            Test0
 setenv compset         HIST_CAM60_CLM50%BGC-CROP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
 # setenv compset         FHIST_DARTC6
-setenv resolution      f09_f09
-setenv cesmtag         cesm2_1
+setenv resolution      f09_f09_mg17
+setenv cesmtag         cesm2_1_relsd_m5.6
 # If cemstag >= cesm2_0_alpha10f and compset = FHIST_DARTC6 (or another non-supported):
 setenv compset_args   "--compset $compset"
 setenv compset_args   "${compset_args} --run-unsupported"
@@ -168,7 +168,7 @@ setenv compset_args   "${compset_args} --run-unsupported"
 #               https://github.com/ESCOMP/cesm.
 # sourcemods    DART does not require a SourceMods directory in order to work with CESM.
 #               If you have modifications to CESM (including bug fixes), they should be provided 
-#               CESM-structured SourceMods directory, which this script expects to be in
+#               in a CESM-structured SourceMods directory, which this script expects to be in
 #               $user/$cesmtag/SourceMods.  Contact dart@ucar.edu for existing SourceMods.
 # caseroot      The CESM $CASEROOT directory, where the CESM+DART configuration files
 #               will be stored and the build commands will be executed.
@@ -222,7 +222,7 @@ setenv baseobsdir   /glade/p/cisl/dares/Observations/Synthetic/UVTRadiosonde_345
 # refyear    The specific date/time-of-day in the reference case that this
 # refmon     run will start from.  (Also see 'runtime settings' below for
 # refday     start_year, start_mon, start_day and start_tod.)
-# reftod
+# reftod     NOTE; there must be obs_seq.in files for these dates.
 # NOTE:      All the ref* variables must be treated like strings and have
 #            the appropriate number of preceeding zeros. 
 #
@@ -303,14 +303,18 @@ set nthreads = 1
 # Examples are provided here.
 # "2 degree":
 # setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_1.9x2.5_1850_2016_c170525.nc
-# setenv sst_grid ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
+# setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv1.9x2.5_gx1v7.170518.nc
 # "1 degree":
-setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2016_c170525.nc
-# sst_grid ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
+setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2020_c210521.nc
+setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v7.151020.nc
 # Specify the beginning and ending years of the data set.
 setenv sst_year_start 1850
-setenv sst_year_end   2016
+setenv sst_year_end   2021
 
+if ($start_year > $sst_year_end) then
+   echo "ERROR: start_year is later then sst_year_end"
+   exit 6
+endif
 
 # ==============================================================================
 # job settings:
@@ -320,6 +324,7 @@ setenv sst_year_end   2016
 # queue      can be changed during a series by changing the case.run
 # timewall   can be changed during a series by changing the case.run
 # ==============================================================================
+
 setenv PROJECT      YOUR_ACCOUNT
 setenv queue        queue_for_assimilation_jobs
 setenv timewall     1:00
@@ -362,6 +367,8 @@ if ($?LS_SUBCWD) then
 else if ($?PBS_O_WORKDIR) then
    cd $PBS_O_WORKDIR
 endif
+echo "Using the starred branch of `pwd`"
+git branch
 
 # Store the location of these setup scripts for use in DART_config.
 set DART_CESM_scripts = `pwd`
@@ -940,11 +947,11 @@ while ($inst <= 1)
    # which prevents the hybrid-mode model from restarting.
    # CESM2_0 and, or, CLM5: is that still true?
 
-   echo "hist_empty_htapes = .true."   >> ${fname}
-   echo "hist_fincl1 = 'TSA'"          >> ${fname}
-   echo "hist_nhtfrq = -$stop_n"       >> ${fname}
-   echo "hist_mfilt  = 1"              >> ${fname}
-   echo "hist_avgflag_pertape = 'I'"   >> ${fname}
+   echo "hist_empty_htapes = .true."                 >> ${fname}
+   echo "hist_fincl1 = 'TSA'"                        >> ${fname}
+   echo "hist_nhtfrq = -$stop_n"                     >> ${fname}
+   echo "hist_mfilt  = 1"                            >> ${fname}
+   echo "hist_avgflag_pertape = 'I'"                 >> ${fname}
 
    # This was needed to allow the interpolation of the default CLM restart file.
    # It is needed in runs that start from a somewhat spun up ensemble.
@@ -983,6 +990,7 @@ while ($inst <= 1)
    @ inst ++
 
 end
+echo ' '
 
 # ===========================================================================
 # set fname = "user_nl_cpl"
