These scripts handle the FV case by default. The input.nml has a separate (commented out) block for SE configurations. The perfect_model.csh, assimilate.csh and CESM_DART_config can handle FV, SE, and WACCM configurations with no modification.
The instructions how to modify the CESM*setup* scripts for SE and WACCM
configurations will be put in the model_mod.html to keep them from 
invading already-complicated 'simple' versions of the setup scripts.

There is a new SourceMods tarfile 
http://www.image.ucar.edu/pub/DART/CESM/DART_SourceMods_cesm1_1_1_19Mar2015.tar
that has a modified lt_archive.sh as well as a src.cam/dynamics/fv/cd_core.F90
that helps stabilize WACCM runs but is not recommended to be used for non-WACCM 
cases. The scripts automatically install or remove cd_core.F90 as needed.



git-svn-id: https://svn-dares-dart.cgd.ucar.edu/DART/trunk@7742 dfa8782c-da17-4c45-ba5c-5625b50a00d6

Former-commit-id: 7f29ec685cdb865d660b2a7be2ce7626620e2de2

diff --git a/models/cam/shell_scripts/CESM1_1_1_setup_pmo b/models/cam/shell_scripts/CESM1_1_1_setup_pmo
--- a/models/cam/shell_scripts/CESM1_1_1_setup_pmo
+++ b/models/cam/shell_scripts/CESM1_1_1_setup_pmo
@@ -15,7 +15,8 @@
 # This script is designed to set up, stage, and build a single-instance run
 # of CESM using an F compset where CAM, CLM and CICE are active. The initial state
 # can come from a single multi-instance reference case so a CESM hybrid setup
-# is used.
+# is used. Instructions on what to change to use the SE core or WACCM are
+# outlined in the models/cam/model_mod.html documentation.
 #
 # DOCN: We are using a single data ocean.
 #
@@ -105,11 +106,12 @@
 # compset       Must be one of the CESM standard names, see the CESM documentation
 #               for supported strings.
 # resolution    Sets the model grid resolution, see the CESM documentation.
+#               f09_f09  ... FV core at ~ 1 degree
+#               BUG 1384 applies here, so ocean and atm/land must be at same resolution.
 # cesmtag       The version of the CESM source code to use when building the code.
 #
-# BUG 1384 applies here, so ocean and atm/land must be at same resolution.
-#   0.9x1.25_0.9x1.25 (f09_f09).  This is roughly a 1 deg grid for atm/lnd,
-#   gx1v6 mask. Normally used for CAM with prescribed lnd, ocn and ice.
+# Guidelines on what to change for an SE or WACCM run are described in the 
+# models/cam/model_mod.html documentation.
 # ==============================================================================
 
 setenv case                 cam1_1_1_pmo
@@ -147,7 +149,7 @@ setenv caseroot     /glade/p/work/${USER}/cases/${case}
 setenv rundir       /glade/scratch/${USER}/${case}/run
 setenv exeroot      /glade/scratch/${USER}/${case}/bld
 setenv archdir      /glade/scratch/${USER}/archive/${case}
-setenv dartroot     /glade/u/home/${USER}/svn/DART/trunk
+setenv dartroot     /glade/u/home/${USER}/svn/DART
 
 # ==============================================================================
 # configure settings:
@@ -159,23 +161,29 @@ setenv dartroot     /glade/u/home/${USER}/svn/DART/trunk
 # refmon     run will start from.  (Also see 'runtime settings' below for
 # refday     start_year, start_mon, start_day and start_tod.)
 # reftod
+# NOTE:      all the ref* variables must be treated like strings and have
+#            the appropriate number of preceeding zeros 
 #
-# SingleInstanceRefcase
+# MultiInstanceRefcase
 #            Filenames from a multi-instance CESM run have an instance number
 #            in them.  Filenames from a single instance CESM run do not.
 #            Setting this helps the script figure out the right filenames to
-#            generate when copying files from the refernenc case:
-#               1 means the restart files have no instance numbers.
-#               0 means the restart files have strings like .0001. in their names.
+#            generate when copying files from the reference case:
+#              'true' means the restart files have strings like .0001. in their names.
+#              'false' the restart files have no instance numbers.
 #
 # TRUTHinstance
-#            If SingleInstanceRefcase is 0, this must be set to select the
+#            If MultiInstanceRefcase is 'true', this must be set to select the
 #            specific instance you want to use when selecting one instance from
 #            a multi-instance run.  e.g. If you have a reference case run
 #            with 80 instances, 1<= TRUTHinstance <= 80. NO LEADING ZEROS.
 #
 # stagedir   The directory location of the reference case files.
 # ==============================================================================
+# alternative reference case for different times may be available here:
+# or on the HPSS:
+# /CCSM/dart/FV0.9x1.25x30_cesm1_1_1/{Mon}1         for 1-degree FV ensembles
+# setenv stagedir /glade/scratch/${USER}/archive/${refcase}/rest/${reftimestamp}
 
 setenv refcase     cesm_hybrid
 setenv refyear     2004
@@ -183,17 +191,14 @@ setenv refmon      01
 setenv refday      10
 setenv reftod      00000
 
-setenv SingleInstanceRefcase 0
-setenv TRUTHinstance 23
+setenv MultiInstanceRefcase true
+setenv TRUTHinstance 1
 
 # useful combinations of time that we use below
 setenv refdate      $refyear-$refmon-$refday
 setenv reftimestamp $refyear-$refmon-$refday-$reftod
 
 setenv stagedir /glade/p/image/CESM_initial_ensemble/rest/${reftimestamp}
-
-# alternative reference case for different times may be available here:
-# setenv stagedir /glade/p/work/raeder/Models/CAM_init/${refcase}_${refdate}
 
 # ==============================================================================
 # runtime settings:
@@ -202,11 +207,6 @@ setenv stagedir /glade/p/image/CESM_initial_ensemble/rest/${reftimestamp}
 # start_month    be different if you want to start this run as if it was a different time.
 # start_day
 # start_tod
-#
-# sst_dataset     Data ocean file and
-# sst_grid        supporting grid file. Must be consistent.
-# sst_year_start  Years included in the sst files.
-# sst_year_end
 #
 # short_term_archiver  Copies the files from each job step to a 'rest' directory.
 # long_term_archiver   Puts the files from all completed steps on tape storage.
@@ -225,12 +225,7 @@ setenv start_month   01
 setenv start_day     10
 setenv start_tod     00000
 
-setenv sst_grid    ${cesmdata}/share/domains/domain.ocn.fv0.9x1.25_gx1v6.130409.nc
-setenv sst_dataset ${cesmdata}/atm/cam/sst/sst_HadOIBl_bc_0.9x1.25_1850_2011_c110307.nc
-setenv sst_year_start    1850
-setenv sst_year_end      2012
-
-setenv short_term_archiver on
+setenv short_term_archiver off
 setenv long_term_archiver  off
 
 setenv resubmit            0
@@ -341,7 +336,7 @@ if ( $status != 0 ) then
    exit -1
 endif
 
-# preserve a copy of this script as it was run
+# Preserve a copy of this script as it was run.
 set ThisFileName = $0:t
 ${COPY} $ThisFileName ${caseroot}/${ThisFileName}.original
 
@@ -357,7 +352,7 @@ if ( ! -e CESM_DART_config ) then
 endif
 
 if (   -e CESM_DART_config ) then
-   sed -e "s#BOGUS_DART_ROOT_STRING#$dartroot#" < CESM_DART_config >! temp.$$
+   sed -e "s#BOGUS_DART_ROOT_STRING#${dartroot}#" < CESM_DART_config >! temp.$$
    ${MOVE} temp.$$ ${caseroot}/CESM_DART_config
    chmod 755       ${caseroot}/CESM_DART_config
 else
@@ -396,17 +391,38 @@ foreach FILE ( *xml )
    endif
 end
 
-   # This is a decent layout for a single instance run.
-   @ atm_tasks = $ptile * 4
-   @ lnd_tasks = $ptile * 4
-   @ ice_tasks = $ptile * 4
-   @ ocn_tasks = $ptile
-   @ cpl_tasks = $ptile
-   @ glc_tasks = $ptile
-   @ rof_tasks = $ptile
+# NOTE: If you require bit-for-bit agreement between different runs,
+#  in particular, between pmo (single instance) and assimilations (NINST > 1),
+#  or if you need to change the number of nodes/member due to changing memory needs,
+#  then env_run.xml:BFBFLAG must be set to TRUE, so that the coupler will
+#  generate bit-for-bit identical results, regardless of the number of tasks
+#  given to it.  The time penalty appears to be ~ 0.5% in the forecast.
+#  Alternatively, you can set cpl_tasks = same_number in both experiments
 
-# echo "task partitioning ... perhaps ... atm // ocn // lnd+ice+glc+rof"
-# presently, all components run 'serially' - one after another.
+# Task layout:
+# Set the nodes_per_instance below to match your case.  If you get 'out of memory' 
+# errors OR failures without any messages, try increasing the nodes_per_instance.
+# CAM-FV 1 degree can run on 2 nodes/instance on yellowstone.
+# CAM-SE ne30 (~ 1 degree) needed 5 nodes/instance.
+# By computing task counts like we do below, we guarantee each instance uses 
+# a whole number of nodes which is the recommended configuration.
+
+# Yellowstone: no large memory nodes, and 15 tasks/node is recommended.
+#       Edwards says there's no speed up by running non-active components concurrently,
+#       after ATM has run, so just run all components sequentially.
+#       BUT, do arrange it so that each member(instance) spans complete nodes:
+#       modulo(total pe count / number of instances, 15) == 0.
+
+@ nodes_per_instance = 2
+
+@ atm_tasks = $ptile * $nodes_per_instance
+@ lnd_tasks = $ptile * $nodes_per_instance
+@ ice_tasks = $ptile * $nodes_per_instance
+@ ocn_tasks = $ptile
+@ cpl_tasks = $ptile
+@ glc_tasks = $ptile
+@ rof_tasks = $ptile
+
 echo ""
 echo "ATM gets $atm_tasks"
 echo "LND gets $lnd_tasks"
@@ -462,19 +478,13 @@ echo ""
 ./xmlchange EXEROOT=${exeroot}
 ./xmlchange RUNDIR=${rundir}
 
-./xmlchange SSTICE_DATA_FILENAME=$sst_dataset
-./xmlchange SSTICE_GRID_FILENAME=$sst_grid
-./xmlchange SSTICE_YEAR_ALIGN=$sst_year_start
-./xmlchange SSTICE_YEAR_START=$sst_year_start
-./xmlchange SSTICE_YEAR_END=$sst_year_end
-
-# Do not change the CALENDAR or the CONTINUE_RUN
+# Do not change the CALENDAR or the value of CONTINUE_RUN in this script.
 
 ./xmlchange CALENDAR=GREGORIAN
+./xmlchange CONTINUE_RUN=FALSE
 
 ./xmlchange STOP_OPTION=$stop_option
 ./xmlchange STOP_N=$stop_n
-./xmlchange CONTINUE_RUN=FALSE
 ./xmlchange RESUBMIT=$resubmit
 
 ./xmlchange PIO_TYPENAME=pnetcdf
@@ -519,8 +529,9 @@ else
    ./xmlchange DOUT_L_MS=TRUE
 endif
 
-# level of debug output, 0=minimum, 1=normal, 2=more, 3=too much, valid values: 0,1,2,3 (integer)
-
+# DEBUG = TRUE implies turning on run and compile time debugging.
+# INFO_DBUG level of debug output, 0=minimum, 1=normal, 2=more, 3=too much.
+# WARNING: CAM-SE fails if DEBUG=TRUE 
 ./xmlchange DEBUG=FALSE
 ./xmlchange INFO_DBUG=0
 
@@ -582,9 +593,7 @@ endsw
 #    mods and put in the SourceMods subdirectory found in the 'caseroot' directory.
 # ==============================================================================
 
-if (    -d     ~/${cesmtag}/SourceMods ) then
-   ${COPY} -r  ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/
-else
+if ( ! -d ~/${cesmtag}/SourceMods ) then
    echo "ERROR - No SourceMods for this case."
    echo "ERROR - No SourceMods for this case."
    echo "DART requires modifications to several src files."
@@ -593,6 +602,29 @@ else
    echo "untar these into your HOME directory - they will create a"
    echo "~/cesm1_1_1  directory with the appropriate SourceMods structure."
    exit -4
+endif
+
+${COPY} -r  ~/${cesmtag}/SourceMods/* ${caseroot}/SourceMods/ || exit 2
+
+# WACCM benefits from a modified cd_core.F90, but none of the
+# other configurations do. 
+
+setenv WACCM `echo $CCSM_COMPSET | grep CCM`
+if ($status == 0) then
+   echo "Using the modified cd_core.F90 because WACCM is being used."
+else
+   echo "Using the default cd_core.F90"
+   ${REMOVE} -v SourceMods/src.cam/dynamics/${CAM_DYCORE}/cd_core.F90
+endif
+
+# Each CAM dynamical core has its own SourceMods
+set numfiles = `ls -1 SourceMods/src.cam/dynamics/${CAM_DYCORE} | wc -l`
+if ( $numfiles > 0 ) then
+   cd      SourceMods/src.cam
+   ${LINK} dynamics/${CAM_DYCORE}/*F90 .
+   cd      ../..
+else
+   echo "No SourceMods for CAM dycore <${CAM_DYCORE}>."
 endif
 
 # The CESM multi-instance capability is relatively new and still has a few
@@ -612,10 +644,15 @@ if ( -d ~/${cesmtag} ) then
       ${COPY} ${caseroot}/preview_namelists \
               ${caseroot}/preview_namelists.original
    endif
+   if ( ! -e  ${caseroot}/Tools/lt_archive.sh.original ) then
+      ${COPY} ${caseroot}/Tools/lt_archive.sh \
+              ${caseroot}/Tools/lt_archive.sh.original
+   endif
 
    # patch/replace the broken files
-   ${COPY} ~/${cesmtag}/clm.buildnml.csh  ${caseroot}/Buildconf/.
-   ${COPY} ~/${cesmtag}/preview_namelists ${caseroot}/.
+   ${COPY} ~/${cesmtag}/clm.buildnml.csh  ${caseroot}/Buildconf/.   || exit 2
+   ${COPY} ~/${cesmtag}/preview_namelists ${caseroot}/.             || exit 2
+   ${COPY} ~/${cesmtag}/lt_archive.sh     ${caseroot}/Tools/.       || exit 2
 
 endif
 
@@ -663,45 +700,16 @@ while ($inst <= 1)
    echo " nhtfrq        = -$stop_n "                      >> ${fname}
    echo " mfilt         = 1 "                             >> ${fname}
 
-   # Some of the files specified here are because the default files only
-   # contain data through 2005 and we are interested in timeframes after that.
-
    # CAM5 does prognostic aerosols by default (which is expensive).
    # Specifying the following causes CAM to use prescribed aerosols, which is cheaper.
    # Prescribed aerosols on the timescales of interest to assimilation are acceptable.
 
    set chem_datapath = "${cesmdata}/atm/cam/chem/trop_mozart_aero"
 
-   echo " bndtvghg              = '${cesmdata}/atm/cam/ggas/ghg_hist_1765-2009_c100902.nc'" >> ${fname}
-   echo " prescribed_ozone_file = 'ozone_1.9x2.5_L26_1850-2015_rcp45_c101108.nc'"               >> ${fname}
-   echo " tracer_cnst_file      =  'oxid_1.9x2.5_L26_1850-2015_rcp45_c101108.nc'"               >> ${fname}
-
    echo "aerodep_flx_datapath   = '${chem_datapath}/aero'"                                      >> ${fname}
    echo "aerodep_flx_file       = 'aerosoldep_rcp4.5_monthly_1849-2104_0.9x1.25_c100407.nc'"    >> ${fname}
    echo "aerodep_flx_type       = 'CYCLICAL'"                                                   >> ${fname}
    echo "aerodep_flx_cycle_yr   = 2000"                                                         >> ${fname}
-
-   echo " ext_frc_specifier     = "                                                             >> ${fname}
-   echo " 'SO2    -> ${chem_datapath}/emis/ar5_mam3_so2_elev_1850-2010_c20100902_v12.nc',"      >> ${fname}
-   echo " 'bc_a1  -> ${chem_datapath}/emis/ar5_mam3_bc_elev_1850-2010_c20100902_v12.nc',"       >> ${fname}
-   echo " 'num_a1 -> ${chem_datapath}/emis/ar5_mam3_num_a1_elev_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'num_a2 -> ${chem_datapath}/emis/ar5_mam3_num_a2_elev_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'pom_a1 -> ${chem_datapath}/emis/ar5_mam3_oc_elev_1850-2010_c20100902_v12.nc',"       >> ${fname}
-   echo " 'so4_a1 -> ${chem_datapath}/emis/ar5_mam3_so4_a1_elev_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'so4_a2 -> ${chem_datapath}/emis/ar5_mam3_so4_a2_elev_1850-2010_c20100902_v12.nc'"    >> ${fname}
-
-   echo " srf_emis_specifier    = "                                                             >> ${fname}
-   echo " 'DMS    -> ${chem_datapath}/emis/aerocom_mam3_dms_surf_1849-2010_c20100902.nc',"      >> ${fname}
-   echo " 'SO2    -> ${chem_datapath}/emis/ar5_mam3_so2_surf_1850-2010_c20100902_v12.nc',"      >> ${fname}
-   echo " 'SOAG   -> ${chem_datapath}/emis/ar5_mam3_soag_1.5_surf_1850-2010_c20100902_v12.nc'," >> ${fname}
-   echo " 'bc_a1  -> ${chem_datapath}/emis/ar5_mam3_bc_surf_1850-2010_c20100902_v12.nc',"       >> ${fname}
-   echo " 'num_a1 -> ${chem_datapath}/emis/ar5_mam3_num_a1_surf_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'num_a2 -> ${chem_datapath}/emis/ar5_mam3_num_a2_surf_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'pom_a1 -> ${chem_datapath}/emis/ar5_mam3_oc_surf_1850-2010_c20100902_v12.nc',"       >> ${fname}
-   echo " 'so4_a1 -> ${chem_datapath}/emis/ar5_mam3_so4_a1_surf_1850-2010_c20100902_v12.nc',"   >> ${fname}
-   echo " 'so4_a2 -> ${chem_datapath}/emis/ar5_mam3_so4_a2_surf_1850-2010_c20100902_v12.nc'"    >> ${fname}
-
-   echo " solar_data_file = '${cesmdata}/atm/cam/solar/spectral_irradiance_Lean_1610-2009_ann_c100405.nc'" >> ${fname}
 
    # ===========================================================================
    set fname = "user_nl_clm${inst_string}"
@@ -717,9 +725,11 @@ while ($inst <= 1)
    #
    # Making a (compact) .h0. file is a good idea, since the clm restart files
    # do not have all the metadata required to reconstruct a gridded field.
-   # 'TSA' is 2m surface air temperature.
+   # 'TSA' is 2m surface air temperature.  This also prevents
+   # having truly empty history files, resulting in ntapes = 0,
+   # which prevents the hybrid-mode model from restarting.
    #
-   # Every 6 hours
+   # Every stop_n hours
    # echo "hist_mfilt  = 1"              >> ${fname}
    # echo "hist_nhtfrq = -$stop_n"       >> ${fname}
    # Every month
@@ -730,7 +740,7 @@ while ($inst <= 1)
    echo "hist_fincl1 = 'TSA'"          >> ${fname}
    echo "hist_nhtfrq = -$stop_n"       >> ${fname}
    echo "hist_mfilt  = 1"              >> ${fname}
-   echo "hist_avgflag_pertape = 'A'"   >> ${fname}
+   echo "hist_avgflag_pertape = 'I'"   >> ${fname}
 
    # ===========================================================================
    set fname = "user_nl_cice${inst_string}"
@@ -869,12 +879,12 @@ else     # CONTINUE_RUN == FALSE
 
       set inst_string = ''
 
-      if ( $SingleInstanceRefcase ) then
-         set true_string = ''
-         echo "Staging initial files."
-      else
+      if ( $MultiInstanceRefcase == 'true') then
          set true_string = `printf _%04d $TRUTHinstance`
          echo "Staging initial files from instance $TRUTHinstance for the truth run."
+      else
+         set true_string = ''
+         echo "Staging initial files."
       endif
 
       ${LINK} ${stagedir}/${refcase}.clm2\${true_string}.r.${init_time}.nc \
