small cirrus test

diff --git a/.github/actions/build_run_model/action.yml b/.github/actions/build_run_model/action.yml
--- a/.github/actions/build_run_model/action.yml
+++ b/.github/actions/build_run_model/action.yml
@@ -22,6 +22,11 @@ inputs:
     description: 'arguments to use when running specified program'
     required: false
     default: ''
+  compiler:
+    description: 'compiler to use when building and running model'
+    type: string
+    required: false
+    default: gfortran
   use-mpi:
     description: 'specify whether to run program without MPI, with MPI, or with MPIF08'
     type: string
@@ -40,9 +45,24 @@ runs:
     - name: Creating Makefile template :)
       run: |
         cd build_templates
-        cp mkmf.template.gfortran mkmf.template
-        echo 'FFLAGS = -g -Wuninitialized -Wunused -ffree-line-length-none -fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow $(INCS)' >> mkmf.template
-      shell: bash
+        case ${{ inputs.compiler }} in
+          gfortran)
+            cp mkmf.template.gfortran mkmf.template
+            echo 'FFLAGS = -g -Wuninitialized -Wunused -ffree-line-length-none -fbounds-check -fbacktrace -ffpe-trap=invalid,zero,overflow $(INCS)' >> mkmf.template
+            ;;
+          cce)
+            cp mkmf.template.cce mkmf.template
+            echo 'FFLAGS  = -O2 -hfp0 $(INCS)' >> mkmf.template
+            ;;
+          nvhpc)
+            cp mkmf.template.nvhpc mkmf.template
+            echo 'FFLAGS = -gopt -C -traceback -Ktrap=fp  -Mbackslash -Kieee $(INCS)' >> mkmf.template
+            ;;
+          *)
+            echo "Unknown compiler: ${{ inputs.compiler }}" >&2
+            exit 1
+            ;;
+        esac
     # Steps to compile and build model
     - name: Building ${{ inputs.model }} model (use-mpi=nompi)
       if: ${{ inputs.use-mpi == 'nompi' }}
@@ -55,29 +75,24 @@ runs:
       run: |
         cd ${{ inputs.models-directory }}/${{ inputs.model }}/work
         ./quickbuild.sh
-      shell: bash
     - name: Building ${{ inputs.model }} model (use-mpi=mpif08)
       if: ${{ inputs.use-mpi == 'mpif08' }}
       run: |
         cd ${{ inputs.models-directory }}/${{ inputs.model }}/work
         ./quickbuild.sh mpif08
-      shell: bash
     # Steps to run the specified run-program with mpi options
     - name: Running ${{ inputs.model }} ${{ inputs.run-program }} program (use-mpi=nompi)
       if: ${{ inputs.use-mpi == 'nompi' }}
       run: |
         cd ${{ inputs.models-directory }}/${{ inputs.model }}/work/
         ./${{ inputs.run-program }} ${{ inputs.run-program-args }}
-      shell: bash
     - name: Running ${{ inputs.model }} ${{ inputs.run-program }} program (use-mpi=mpi)
       if: ${{ inputs.use-mpi == 'mpi' }}
       run: |
         cd ${{ inputs.models-directory }}/${{ inputs.model }}/work/
         mpirun -n ${{ inputs.mpi-n-tasks }} ./${{ inputs.run-program }} ${{ inputs.run-program-args }}
-      shell: bash
     - name: Running ${{ inputs.model }} ${{ inputs.run-program }} program (use-mpi=mpif08)
       if: ${{ inputs.use-mpi == 'mpif08' }}
       run: |
         cd ${{ inputs.models-directory }}/${{ inputs.model }}/work/
         mpirun -n ${{ inputs.mpi-n-tasks }} ./${{ inputs.run-program }} ${{ inputs.run-program-args }}
-      shell: bash
